[package]
name = "multiplatform_test"
publish = true
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/multiplatform_test/"
description = "A simple attribute macro to combine `#[test]` and `#[wasm_bindgen_test]`"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
