[package]
name = "hydroflow_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
hydroflow_lang = { path = "../hydroflow_lang" }
proc-macro2 = "1.0.0"
proc-macro-crate = "1.1.0"
quote = "1.0.0"
syn = { version = "1.0.0", features = [ "parsing", "extra-traits" ] }

[build-dependencies]
hydroflow_lang = { path = "../hydroflow_lang" }
quote = "1.0.0"
