[workspace]

members = [
    # When adding a new crate which is published, you need to:
    # 1. Commit an (empty) file `my_crate/CHANGELOG.md`.
    # 2. Ensure `publish = true` and other required fields (`license`, `description`, `documentation`,
    #    etc.), are set in `my_crate/Cargo.toml`
    #    https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate
    # 3. Ensure any `path` dependencies to/from `my_crate` also include `version = "^0.1.0"`
    #    (substitute correct version).
    # Then just run the release workflow as normal.
    "benches",
    "hydro_cli",
    "hydro_cli_examples",
    "hydroflow",
    "hydroflow_cli_integration",
    "hydroflow_datalog",
    "hydroflow_datalog_core",
    "hydroflow_lang",
    "hydroflow_macro",
    "lattices",
    "multiplatform_test",
    "pusherator",
    "relalg",
    "topolotree",
    "variadics",
    "website_playground",
]

resolver = "2"

[profile.release]
strip = true      # Strip symbols from the binary
# Previously this was "z" to minimize docker binary size while sacrificing performance. But "z"
# doesn't make things that much smaller, `strip` is far more important for binary size. Use "3" for
# performance.
opt-level = 3
lto = "fat"

[profile.profile]
inherits = "release"
debug = 2
strip = "none"

[profile.dev.package.website_playground]
debug-assertions = false

[profile.release.package.website_playground]
opt-level = "s"
