[workspace]

members = [
    "hydroflow_internalmacro",
    "hydroflow_lang",
    "hydroflow_macro",
    "hydroflow",
    "hydroflow_datalog_core",
    "hydroflow_datalog",
    "benches",
    "relalg",
    "pusherator",
    "variadics",
]

[profile.release]
strip = true      # Strip symbols from the binary
opt-level = 3   # Optimize for size

[profile.profile]
inherits = "release"
opt-level = 3
panic = "abort"
debug = 2
strip = "none"
