[workspace]

members = [
    "hydroflow",
    "hydroflow_lang",
    "hydroflow_macro",
    "hydroflow_datalog",
    "benches",
    "relalg",
    "pusherator",
    "type_list",
]

[profile.release]
strip = true      # Strip symbols from the binary
opt-level = "z"   # Optimize for size
