[workspace]

members = [
    "hydroflow_internalmacro",
    "hydroflow_lang",
    "hydroflow_macro",
    "hydroflow",
    "hydroflow_datalog",
    "benches",
    "relalg",
    "pusherator",
    "type_list",
]
