[workspace]

members = [
    "hydroflow_internalmacro",
    "hydroflow_lang",
    "hydroflow_macro",
    "hydroflow",
    "hydroflow_datalog_core",
    "hydroflow_datalog",
    "benches",
    "relalg",
    "pusherator",
    "variadics",
]

[profile.release]
strip = true      # Strip symbols from the binary
opt-level = "z"   # Optimize for size

[profile.profile]
inherits = "release"
debug = 2
strip = "none"
