[workspace]

members = [
    # When adding a new crate which is published, you will need to run
    # `cargo changelog --write my_crate` and edit `my_crate/CHANGELOG.md` and change
    # `## Unreleased` to `## 0.0.0 (2023-05-02)` (use current date) before running the release
    # workflow.
    "benches",
    "hydro_cli",
    "hydro_cli_examples",
    "hydroflow",
    "hydroflow_cli_integration",
    "hydroflow_datalog",
    "hydroflow_datalog_core",
    "hydroflow_internalmacro",
    "hydroflow_lang",
    "hydroflow_macro",
    "lattices",
    "multiplatform_test",
    "pusherator",
    "relalg",
    "variadics",
]

resolver = "2"

[profile.release]
strip = true      # Strip symbols from the binary
# Previously this was "z" to minimize docker binary size while sacrificing performance. But "z"
# doesn't make things that much smaller, `strip` is far more important for binary size. Use "3" for
# performance.
opt-level = 3
lto = "fat"

[profile.profile]
inherits = "release"
debug = 2
strip = "none"
