[package]
name = "hydro_cli"
version = "0.1.0"
edition = "2021"

[[example]]
name = "simple"

[dependencies]
tokio = { version = "1.16", features = [ "full" ] }
clap = { version = "4.1.4", features = ["derive"] }
cargo = "0.68.0"
pyo3 = { version = "0.18.1", features = ["auto-initialize"] }
pyo3-asyncio = { version = "0.18.0", features = ["attributes", "unstable-streams", "tokio-runtime"] }
async-trait = "0.1.64"
async-process = "1.6.0"
futures = "0.3.26"
futures-core = "0.3.26"
async-channel = "1.8.0"

[dev-dependencies]
