import HydroV2.HydroGen

/-!
# HydroV2 · `HydroGen` knot generation (`hydro_knot`)

The knot stack for a `HydroSem.fix`/`fixTick` wrapper, generalized to
the real program shapes (D44 handoff): **leg-selected** bodies
(`(pcBody …).2.2.1`, `(leCore …).fail_ballots`), **composed** bodies
with *inner knots* in argument positions (`leIam` contains
`leFails(f)`; `leFfx` contains `leCore(leFails(leIam f, f), leIam f,
f)`), **tick** knots (`fixTick` over `CoTickSing` gadgets), and
**body-constant** knots (`pcSeqF` — the fix is applied inline by the
program, so the theorems are stated at the `H.fix` application).
(Since D51 the knots and their body constants are auto-generated by
the inline `fix` elaborator as `M.wire` / `M.wire.body`; the
hand-written names above survive as the shape vocabulary.)

Generated artifacts per knot `K` (registered like a module's, so
knot-calling modules consume them through the same registry):

- `K_co_sr₁` — the machine naming `(K @ corner).sr = K @ SchedSem`,
  by the `co_knot_sr` house script (defeq never crosses the knot
  boundary; body legs + inner knots fold through their lemmas).
- `K_co_rr₁` — the denotational naming at the body module's
  choice-`vdec` applied at the knot's own machine wires (the loop
  position takes the *machine knot* — `K @ SchedSem`).
- `K_causal₁` — step causality of the machine knot
  (`causal_fix_stream`/`_tick` over the composed body's causality).
- `K_mono₁` — `Values` monotonicity of the denotational knot at a
  *generic* decision record (`iterate_mono_param` over the body's
  generated monotonicity, inner knots threaded recursively).
- `K_co_wf₁` — the corner `wf` triple (`hcaus ∧ hchain ∧ hcplj`), by
  the validated blueprint with composition-aware facts.

All statements are synthesized from the knot's signature + the parsed
body composition; all proofs are fixed scripts over installed facts
(`Expr`-built lemma applications, rewritten by `kabstract`/`congrArg`
chains — never a whole-program defeq).
-/

namespace HydroV2

open Lean Elab Term Meta Command

namespace HydroGen

/-! ## Proof plumbing (moved from the phase-1 knot section) -/

/-- Prove an OPEN goal (ambient fvars visible to the script) by a
tactic string. -/
def proveByTacOpen (goal : Expr) (tac : String) : TermElabM Expr := do
  let env ← getEnv
  let stx ← match Parser.runParserCategory env `tactic tac with
    | .ok s => pure s
    | .error e => throwError "HydroGen: tactic parse error: {e}\n{tac}"
  Term.withoutErrToSorry do
    let mvar ← mkFreshExprSyntheticOpaqueMVar goal
    let (remaining, _) ← Lean.Elab.runTactic mvar.mvarId!
      (⟨stx⟩ : TSyntax `tactic)
    let remaining ← remaining.filterM fun g => do
      pure (!(← g.isAssigned) && !(← g.isDelayedAssigned))
    unless remaining.isEmpty do
      throwError "HydroGen: unsolved goals ({remaining.length}) \
        under\n{tac}\n{goalsToMessageData remaining}"
    Term.synthesizeSyntheticMVarsNoPostponing
    instantiateMVars mvar

/-- Apply `decl` supplying implicit binders named `pacing`/`Tc`/`Td`/
`hjT` from the given values (they cannot be unified from
machine-typed argument types), explicits from `explicits`; other
implicits by unification, instances synthesized at the end. -/
def applyNamed (decl : Name) (pacing Tc Td hjT : Expr)
    (explicits : Array Expr) : TermElabM Expr := do
  let info ← getConstInfo decl
  let us ← info.levelParams.mapM fun _ => mkFreshLevelMVar
  let mut e := Expr.const decl us
  let mut ty := info.type.instantiateLevelParams info.levelParams us
  let mut queue := explicits.toList
  let mut instMVars : Array MVarId := #[]
  while true do
    ty ← whnfR (← instantiateMVars ty)
    unless ty.isForall do break
    let bi := ty.bindingInfo!
    let nm := ty.bindingName!
    let d := ty.bindingDomain!
    let mut arg := default
    if bi.isExplicit then
      match queue with
      | a :: rest =>
        queue := rest
        unless ← isDefEq (← inferType a) d do
          throwError "applyNamed {decl}: arg {a} type mismatch \
            against {d}"
        arg := a
      | [] => break
    else if nm == `pacing then arg := pacing
    else if nm == `Tc then arg := Tc
    else if nm == `Td then arg := Td
    else if nm == `hjT then arg := hjT
    else if bi.isInstImplicit then
      let m ← mkFreshExprMVar d
      instMVars := instMVars.push m.mvarId!
      arg := m
    else
      arg := ← mkFreshExprMVar d
    e := mkApp e arg
    ty := ty.bindingBody!.instantiate1 arg
  for m in instMVars do
    unless ← m.isAssigned do
      let v ← synthInstance (← instantiateMVars (← m.getType))
      m.assign v
  let out ← instantiateMVars e
  if out.hasExprMVar then
    throwError "applyNamed {decl}: metavariables remain in {out}"
  pure out

/-- Normalize gadget projections in a fact's TYPE (the projection
lemmas are all `rfl`, so re-typing is a defeq hint). -/
def collapseFact (prf : Expr) : TermElabM Expr := do
  let names := #[``co_mkC_sr, ``co_mkC_rr, ``co_lowerC_sr,
    ``co_lowerC_rr, ``co_probeC_sr, ``co_probeC_rr,
    ``co_schedC_sr, ``co_probe2_sr, ``co_probe2_rr,
    ``co_schedEmbed_sr, ``co_tick_lowerC_sr, ``co_tick_lowerC_rr,
    ``co_tick_probe2_sr, ``co_tick_probe2_rr,
    ``co_tick_schedEmbed_sr, ``co_mkC_sr_raw, ``co_mkC_rr_raw,
    ``co_tick_mkC_sr_raw, ``co_tick_mkC_rr_raw,
    ``co_tick_schedC_sr, ``co_tick_probeC_sr, ``co_tick_probeC_rr]
  let mut st : SimpTheorems := {}
  for n in names do
    if (← getEnv).contains n then
      st ← st.addConst n
  let ctx ← Simp.mkContext (simpTheorems := #[st])
  let ty ← inferType prf
  let (res, _) ← simp ty ctx
  mkExpectedTypeHint prf res.expr

/-- Rewrite occurrences of `eq`'s LHS *inside the RHS* of the equation
proof `base` (`base : a = b`, `eq : c = d` ⟹ `a = b[c := d]`), by
`kabstract`/`congrArg`/`Eq.trans`. No-op when the pattern is absent. -/
def rwRhs (base : Expr) (eq : Expr) : TermElabM Expr := do
  let bTy ← whnfR (← inferType base)
  let some (_, _lhs, rhs) := bTy.eq? |
    throwError "HydroGen: rwRhs base is not an equation ({bTy})"
  let eTy ← whnfR (← inferType eq)
  let some (_, c, _d) := eTy.eq? |
    throwError "HydroGen: rwRhs eq is not an equation"
  let rhsAbs ← kabstract rhs c
  unless rhsAbs.hasLooseBVars do
    return base
  let motive := Expr.lam `w (← inferType c) rhsAbs .default
  let step ← mkCongrArg motive eq
  mkEqTrans base step

def rwRhsAll (base : Expr) (eqs : Array Expr) : TermElabM Expr := do
  let mut b := base
  for e in eqs do
    b ← rwRhs b e
  pure b

/-! ## Residual callee rewriting (spec-directed)

`simp` cannot rewrite a callee redex sitting in a *dependent*
argument position (e.g. `leBody`'s subtype output mentions its `ff`
wire, so the congruence for that argument has no motive). The redex
is still rewritable at the equation level: `kabstract` over the
equation's RHS — whose type does not depend on the argument once the
`.val`/leg projections are outside. These helpers find lemma-LHS
matches by unification and push them through `rwRhs`. -/

/-- A pattern key: the LHS head shape of a rewrite lemma (projection
flag, head constant, arity). Candidate lookup is a single keyed scan
per round instead of one full-term scan per lemma. -/
structure LemKey where
  isProj : Bool
  head : Name
  arity : Nat
  deriving BEq, Hashable

def lemKeyOf (lem : Name) : TermElabM LemKey := do
  let lemC ← mkConstWithFreshMVarLevels lem
  forallTelescopeReducing (← inferType lemC) fun _ ty => do
    let some (_, lhs, _) := ty.eq?
      | throwError "HydroGen: {lem} is not an equation"
    match lhs with
    | .proj _ _ s =>
      let .const c _ := s.getAppFn
        | throwError "HydroGen: {lem}: opaque projection LHS"
      pure ⟨true, c, s.getAppNumArgs⟩
    | _ =>
      let .const c _ := lhs.getAppFn
        | throwError "HydroGen: {lem}: opaque LHS head"
      pure ⟨false, c, lhs.getAppNumArgs⟩

private def keyOfTerm (e : Expr) : Option LemKey :=
  match e with
  | .proj _ _ s =>
    match s.getAppFn with
    | .const c _ => some ⟨true, c, s.getAppNumArgs⟩
    | _ => none
  | .app .. =>
    match e.getAppFn with
    | .const c _ => some ⟨false, c, e.getAppNumArgs⟩
    | _ => none
  | _ => none

/-- One scan: closed subterms bucketed by pattern key. -/
private partial def collectKeyed (e : Expr) :
    Std.HashMap LemKey (Array Expr) :=
  go e {}
where
  go (e : Expr) (acc : Std.HashMap LemKey (Array Expr)) :
      Std.HashMap LemKey (Array Expr) :=
    let acc := match keyOfTerm e with
      | some k =>
        if e.hasLooseBVars then acc
        else acc.insert k ((acc.getD k #[]).push e)
      | none => acc
    match e with
    | .app f a => go a (go f acc)
    | .lam _ d b _ => go b (go d acc)
    | .forallE _ d b _ => go b (go d acc)
    | .letE _ t v b _ => go b (go v (go t acc))
    | .mdata _ b => go b acc
    | .proj _ _ b => go b acc
    | _ => acc

/-- Match the ∀-lemma's equation LHS against a candidate (unification
with fresh metavariables at reducible transparency — pattern matching
must not delta-unfold module bodies on near-misses); return the
instantiated equation proof. -/
def matchLemma (lem : Name) (cand : Expr) : TermElabM (Option Expr) := do
  observing? do
    let lemC ← mkConstWithFreshMVarLevels lem
    let (ms, _, ty) ← forallMetaTelescope (← inferType lemC)
    let some (_, lhs, _) := ty.eq?
      | throwError "HydroGen: {lem} is not an equation"
    unless ← withReducible <| isDefEq lhs cand do
      throwError "no match"
    for m in ms do
      unless ← m.mvarId!.isAssigned do
        let mty ← instantiateMVars (← m.mvarId!.getType)
        m.mvarId!.assign (← synthInstance mty)
    instantiateMVars (mkAppN lemC ms)

/-- A tracked equation-proof chain `prf : lhs = rhs` (carrier `α :
Sort u`). Tracking `rhs` avoids re-inferring the growing proof's type
on every rewrite step. -/
structure RwSt where
  prf : Expr
  lhs : Expr
  rhs : Expr
  α : Expr
  u : Level

def RwSt.ofProof (prf lhs rhs : Expr) : TermElabM RwSt := do
  let α ← inferType lhs
  pure { prf, lhs, rhs, α, u := ← getLevel α }

/-- One tracked rewrite: `eqPrf : c = d` replaces all occurrences of
`c` in `rhs` (`Eq.trans`/`congrArg` assembled manually — no proof-
chain type inference). Returns `none` when the pattern is absent. -/
def RwSt.rwStep (st : RwSt) (eqPrf : Expr) :
    TermElabM (Option RwSt) := do
  let eTy ← whnfR (← inferType eqPrf)
  let some (γ, c, d) := eTy.eq? | return none
  -- reducible: the pattern is syntactically present (found by the
  -- reducible matcher); default-transparency near-miss comparisons
  -- against module-sized subterms are the classic whnf blowup
  let rhsAbs ← withReducible <| kabstract st.rhs c
  unless rhsAbs.hasLooseBVars do return none
  let motive := Expr.lam `w γ rhsAbs .default
  let uγ ← getLevel γ
  let step := mkApp6 (.const ``congrArg [uγ, st.u]) γ st.α c d
    motive eqPrf
  let rhs' := rhsAbs.instantiate1 d
  let prf' := mkApp6 (.const ``Eq.trans [st.u]) st.α st.lhs st.rhs
    rhs' st.prf step
  pure (some { st with prf := prf', rhs := rhs' })

/-- First structurally divergent subterm pair (for meet-check
diagnostics — the pretty printer hides instances/universes/mdata). -/
partial def exprDiff (a b : Expr) : Option (Expr × Expr) :=
  if a == b then none
  else match a, b with
    | .app f₁ a₁, .app f₂ a₂ =>
      (exprDiff f₁ f₂).orElse fun _ => exprDiff a₁ a₂
    | .lam _ d₁ b₁ _, .lam _ d₂ b₂ _ =>
      (exprDiff d₁ d₂).orElse fun _ => exprDiff b₁ b₂
    | .forallE _ d₁ b₁ _, .forallE _ d₂ b₂ _ =>
      (exprDiff d₁ d₂).orElse fun _ => exprDiff b₁ b₂
    | .letE _ t₁ v₁ b₁ _, .letE _ t₂ v₂ b₂ _ =>
      ((exprDiff t₁ t₂).orElse fun _ => exprDiff v₁ v₂).orElse
        fun _ => exprDiff b₁ b₂
    | .mdata _ e₁, .mdata _ e₂ => some ((exprDiff e₁ e₂).getD (a, b))
    | .proj _ _ e₁, .proj _ _ e₂ => some ((exprDiff e₁ e₂).getD (a, b))
    | _, _ => some (a, b)

def meetError (mName : Name) (what : String) (tC tR : Expr) :
    TermElabM Expr := do
  match exprDiff tC tR with
  | some (dA, dB) =>
    throwError "HydroGen: {mName}: {what} does not meet; first \
      divergence:\ncorner node ({dA.ctorName}): {dA}\nmodule node \
      ({dB.ctorName}): {dB}"
  | none =>
    throwError "HydroGen: {mName}: {what} does not meet (no \
      structural diff?!)"

/-- Match memo: results depend only on `(lemma, candidate)` — shared
across rounds AND legs (wire projections recur in every leg). -/
abbrev MatchCache := IO.Ref (Std.HashMap (Name × Expr) (Option Expr))

def matchLemmaC (cache : MatchCache) (lem : Name) (cand : Expr) :
    TermElabM (Option Expr) := do
  if let some r := (← cache.get).get? (lem, cand) then
    return r
  let r ← matchLemma lem cand
  cache.modify (·.insert (lem, cand) r)
  pure r

/-- Rewrite by the lemma set to fixpoint: per round, ONE keyed scan
buckets the closed subterms; each lemma only tries candidates under
its own key (a stale candidate after an earlier rewrite in the same
round just no-ops at `kabstract`). Fresh redexes exposed by a rewrite
are picked up by the next round. -/
def RwSt.rwResiduals (st : RwSt) (lems : Array (Name × LemKey))
    (cache : MatchCache) : TermElabM RwSt := do
  let mut st := st
  for _ in [0:8] do
    let mut changed := false
    let table := collectKeyed st.rhs
    for (lem, key) in lems do
      if let some cands := table.get? key then
        for cand in cands do
          if let some eqPrf ← matchLemmaC cache lem cand then
            if let some st' ← st.rwStep eqPrf then
              st := st'
              changed := true
    unless changed do break
  pure st

/-! ## Gadget vocabulary (stream vs tick) -/

structure KGad where
  isTick : Bool
  schedC : Name
  probeC : Name
  mkC : Name
  lowerC : Name
  fixSr : Name
  sbody : Name
  vbody : Name
  schedHfix' : Name
  agree : Name

def gadStream : KGad :=
  { isTick := false, schedC := ``CoStream.schedC,
    probeC := ``CoStream.probeC, mkC := ``CoStream.mkC,
    lowerC := ``CoStream.lowerC, fixSr := ``CoStream.fixSr,
    sbody := ``CoStream.sbody, vbody := ``CoStream.vbody,
    schedHfix' := ``sched_hfix_stream', agree := ``SAgree }

def gadTick : KGad :=
  { isTick := true, schedC := ``CoTickSing.schedC,
    probeC := ``CoTickSing.probeC, mkC := ``CoTickSing.mkC,
    lowerC := ``CoTickSing.lowerC, fixSr := ``CoTickSing.fixSr,
    sbody := ``CoTickSing.sbody, vbody := ``CoTickSing.vbody,
    schedHfix' := ``sched_hfix_tick', agree := ``TAgree }

/-! ## The body composition -/

/-- A knot-body argument (positions after the interpretation). -/
inductive BArg where
  /-- The loop wire. -/
  | gadget
  /-- Closed over the knot's fvars (wire/decision/plain). -/
  | expr (e : Expr)
  /-- An inner-knot application (contains the loop wire); index into
  the flat inner table. -/
  | inner (idx : Nat)
  deriving Inhabited, Repr

/-- An inner-knot application, kept as the ORIGINAL `Expr` over the
loop fvar (instances preserved), plus its parsed argument view. -/
structure InnerApp where
  kName : Name
  gi : GenInfo
  /-- Args strictly before the interpretation instance (closed). -/
  preArgs : Array Expr
  /-- Explicit args after the interpretation. -/
  args : Array BArg
  kinds : Array ArgKind
  /-- The original application over the loop fvar (at the corner). -/
  app : Expr
  deriving Inhabited

/-- The parsed knot body: a leg-selected registered-module application
whose arguments may contain inner knots. -/
structure BodyComp where
  bodyMod : Name
  gi : GenInfo
  legPath : List LegStep
  legIdx : Nat
  legsCount : Nat
  /-- Args strictly before the interpretation instance. -/
  preArgs : Array Expr
  args : Array BArg
  kinds : Array ArgKind
  /-- The original module application over the loop fvar. -/
  coreApp : Expr
  inners : Array InnerApp
  /-- Wrapper defs opened while parsing (for `unfold` lists). -/
  unfolded : Array Name
  deriving Inhabited

/-- The `LegStep` for field `i` of structure `s`. -/
def projStepOf (s : Name) (i : Nat) : MetaM LegStep := do
  if s == ``Prod then
    pure (if i == 0 then .fst else .snd)
  else if s == ``Subtype then
    pure .val
  else
    let fields := getStructureFields (← getEnv) s
    pure (.field fields[i]!)

/-- Peel outer projections (const-app form or `Expr.proj`) into a leg
path; returns the operand. -/
partial def peelOuterProj (e : Expr) (acc : List LegStep) :
    MetaM (Expr × List LegStep) := do
  let env ← getEnv
  match e with
  | .proj s i x =>
    let step ← projStepOf s i
    peelOuterProj x (step :: acc)
  | _ =>
    let f := e.getAppFn
    if let .const c _ := f then
      if let some pi := env.getProjectionFnInfo? c then
        let args := e.getAppArgs
        if args.size == pi.numParams + 1 then
          let s := pi.ctorName.getPrefix
          let step ← projStepOf s pi.i
          return ← peelOuterProj args[pi.numParams]! (step :: acc)
    pure (e, acc)

/-- Find the interpretation-instance position among an application's
arguments (the arg whose type's head is `HydroSem`). -/
def interpPosOf (args : Array Expr) : MetaM (Option Nat) := do
  for h : i in [0:args.size] do
    let t ← inferType args[i]
    if t.getAppFn.isConstOf ``HydroSem then
      return some i
  return none

/-- Parse the knot body at `(corner, capsVal, loopFVar)`: peel outer
projections, unfold unregistered wrappers, classify args, recurse into
inner knots. -/
partial def parseKnotBody (corner : Expr) (loopFVar : Expr) (e : Expr) :
    TermElabM BodyComp := do
  let (core, path) ← peelOuterProj e []
  go core path #[]
where
  go (core : Expr) (path : List LegStep) (unfolded : Array Name) :
      TermElabM BodyComp := do
    let core := core.headBeta
    let f := core.getAppFn
    let .const c _ := f |
      throwError "HydroGen: knot body head is not a constant ({core})"
    if let some gi := getGenInfo (← getEnv) c then
      -- registered module: classify
      let args := core.getAppArgs
      let some hPos ← interpPosOf args |
        throwError "HydroGen: body module {c} application has no \
          interpretation argument"
      let mut inners : Array InnerApp := #[]
      let mut bargs : Array BArg := #[]
      let mut kinds : Array ArgKind := #[]
      for i in [hPos+1:args.size] do
        let a0 := args[i]!
        if a0 == loopFVar then
          kinds := kinds.push (← classifyArg corner (← inferType a0))
          bargs := bargs.push .gadget
        else if a0.containsFVar loopFVar.fvarId! then
          kinds := kinds.push (← classifyArg corner (← inferType a0))
          let (ia, inners') ← parseInner a0 inners
          inners := inners'
          bargs := bargs.push (.inner ia)
        else
          let a ← whnf a0
          kinds := kinds.push (← classifyArg corner (← inferType a))
          bargs := bargs.push (.expr a)
      -- leg index: match the path against the module's output legs
      let legs ← legsOfCore core hPos
      let some legIdx := legs.idxOf? path |
        throwError "HydroGen: leg path {repr path} not among \
          {c}'s legs {repr legs}"
      return { bodyMod := c, gi, legPath := path, legIdx,
               legsCount := legs.size,
               preArgs := args[0:hPos].toArray,
               args := bargs, kinds, coreApp := core, inners,
               unfolded }
    else
      -- unregistered wrapper: unfold and re-peel
      let info ← getConstInfo c
      let some v := info.value? |
        throwError "HydroGen: knot body head {c} is not registered \
          and has no value"
      let core' := (v.instantiateLevelParams info.levelParams
        (f.constLevels!)).beta core.getAppArgs
      let (core'', path') ← peelOuterProj core' []
      go core'' (path' ++ path) (unfolded.push c)
  parseInner (a : Expr) (inners : Array InnerApp) :
      TermElabM (Nat × Array InnerApp) := do
    let a := a.headBeta
    let f := a.getAppFn
    let .const c _ := f |
      throwError "HydroGen: inner-knot head is not a constant ({a})"
    let some gi := getGenInfo (← getEnv) c |
      throwError "HydroGen: inner knot {c} is not registered \
        (generate it first)"
    let args := a.getAppArgs
    let some hPos ← interpPosOf args |
      throwError "HydroGen: inner knot {c} has no interpretation arg"
    let mut inners := inners
    let mut bargs : Array BArg := #[]
    let mut kinds : Array ArgKind := #[]
    for i in [hPos+1:args.size] do
      let x0 := args[i]!
      if x0 == loopFVar then
        kinds := kinds.push (← classifyArg corner (← inferType x0))
        bargs := bargs.push .gadget
      else if x0.containsFVar loopFVar.fvarId! then
        kinds := kinds.push (← classifyArg corner (← inferType x0))
        let (ia, inners') ← parseInner x0 inners
        inners := inners'
        bargs := bargs.push (.inner ia)
      else
        let x ← whnf x0
        kinds := kinds.push (← classifyArg corner (← inferType x))
        bargs := bargs.push (.expr x)
    let ia : InnerApp :=
      { kName := c, gi, preArgs := args[0:hPos].toArray,
        args := bargs, kinds, app := a }
    return (inners.size, inners.push ia)
  legsOfCore (core : Expr) (hPos : Nat) : TermElabM (Array (List LegStep)) := do
    -- the module's output legs, from the applied core's type
    let _ := hPos
    let ty ← inferType core
    peelLegs ty []

/-! ## The knot context -/

structure KnotCtx where
  mc : ModCtx
  gad : KGad
  df : Expr
  caps : Expr
  bodyFn : Expr
  /-- The unit-level body `bodyFn corner caps`. -/
  B : Expr
  loopTy : Expr
  loopFVar : Expr
  comp : BodyComp
  /-- For body-constant knots (`pcSeqF`): the fix is applied inline by
  the program; statements are at the `H.fix` application and `df` is a
  fresh binder. -/
  bodyConst : Bool

/-- Extract `(isTick, df, caps, bodyFn)` from the knot def's value. -/
def extractFix2 (mc : ModCtx) : TermElabM (Option (Bool × Expr × Expr × Expr)) := do
  let info ← getConstInfo mc.mName
  let some v := info.value? |
    throwError "HydroGen: {mc.mName} has no value"
  let app := (v.beta (mc.ctxArgs ++ #[mc.corner] ++ mc.args)).headBeta
  let pick := fun (app : Expr) (tick : Bool) => do
    let args := app.getAppArgs
    unless args.size ≥ 3 do
      throwError "HydroGen: {mc.mName}: fix arity {args.size}"
    pure (some (tick, args[args.size - 3]!, args[args.size - 2]!,
      args[args.size - 1]!))
  if app.getAppFn.isConstOf ``HydroSem.fix then return ← pick app false
  if app.getAppFn.isConstOf ``HydroSem.fixTick then return ← pick app true
  if let some app' ← whnfUntil app ``HydroSem.fix then
    return ← pick app' false
  if let some app' ← whnfUntil app ``HydroSem.fixTick then
    return ← pick app' true
  pure none

/-- Open knot `K`'s context: module telescope, fix extraction, body
parse (the loop fvar stays in scope for `k`). -/
def withKnotCtx (mc : ModCtx) (k : KnotCtx → TermElabM α) :
    TermElabM α := do
  let some (isTick, df, caps, bodyFn) ← extractFix2 mc |
    throwError "HydroGen: {mc.mName}: no HydroSem.fix/fixTick at the head"
  unless mc.legs.size == 1 && mc.legs[0]! == [] do
    throwError "HydroGen: hydro_knot expects a bare single-leg knot"
  let gad := if isTick then gadTick else gadStream
  let loopTy := mc.legTys[0]!
  withLocalDecl `zknot .default loopTy fun loopFVar => do
    let bodyAt := (mkApp2 bodyFn mc.corner caps).headBeta
    let bodyOpen := (mkApp bodyAt loopFVar).headBeta
    let comp ← parseKnotBody mc.corner loopFVar bodyOpen
    k { mc, gad, df, caps, bodyFn, B := bodyAt, loopTy, loopFVar, comp,
        bodyConst := false }

/-! ## Valuations over the composition -/

/-- How to value each argument position of the (body/inner) modules
when reconstructing an application at a target interpretation. -/
structure BVal where
  interp : Expr
  /-- The value for the loop position. -/
  gadget : Expr
  /-- Wire args (by raw corner expr). -/
  wire : Expr → TermElabM Expr
  /-- Primitive decisions. -/
  prim : DecFam → Expr → TermElabM Expr
  /-- Decision records. -/
  recd : Expr → TermElabM Expr
  /-- Plain data. -/
  plain : Expr → TermElabM Expr := pure

/-- The machine-side valuation over the knot's own fvars. -/
def BVal.machine (kc : KnotCtx) (gadget : Expr) : BVal :=
  { interp := kc.mc.sched, gadget,
    wire := fun e => mkProjection e `sr,
    prim := fun f e =>
      pure (if f.schedPass then e else mkConst ``Unit.unit),
    recd := fun e => repackRec kc.mc.corner kc.mc.sched
      (fun f p =>
        pure (if f.schedPass then p else mkConst ``Unit.unit)) e }

/-- The lowered-corner valuation (`hcplj`): wires lowered, records
identity-repacked, gadget at `mkC`. -/
def BVal.lowered (kc : KnotCtx) (corner' : Expr) (gadget : Expr)
    (hjE hjT' : Expr) : BVal :=
  { interp := corner', gadget,
    wire := fun e => do
      let lc := if (← whnf (← inferType e)).isAppOf ``CoTickSing then
        ``CoTickSing.lowerC else ``CoStream.lowerC
      applyNamed lc kc.mc.pacing kc.mc.Tc kc.mc.Td kc.mc.hjT
        #[hjE, hjT', e],
    prim := fun _ e => pure e,
    recd := fun e => repackRec kc.mc.corner corner' (fun _ p => pure p) e }

/-- Value a `BArg` under a valuation (inner knots reconstructed at the
valuation's interpretation, recursively). -/
partial def bargVal (kc : KnotCtx) (bv : BVal)
    (a : BArg) (kind : ArgKind) : TermElabM Expr := do
  match a with
  | .gadget => pure bv.gadget
  | .expr e =>
    match kind with
    | .wire _ => bv.wire e
    | .primDec f => bv.prim f e
    | .decRec _ => bv.recd e
    | .plain => bv.plain e
  | .inner idx =>
    let ia := kc.comp.inners[idx]!
    let mut args := #[]
    for a' in ia.args, k' in ia.kinds do
      args := args.push (← bargVal kc bv a' k')
    pure (mkAppN ia.app.getAppFn (ia.preArgs ++ #[bv.interp] ++ args))

/-- Value the body-module argument list under a valuation. -/
def bodyArgsVal (kc : KnotCtx) (bv : BVal) : TermElabM (Array Expr) := do
  let mut out := #[]
  for a in kc.comp.args, k in kc.comp.kinds do
    out := out.push (← bargVal kc bv a k)
  pure out

mutual

/-- An inner app at the corner, at a given gadget value (reduced-args
spelling, consistent with the parse). -/
partial def cornerInnerAt (kc : KnotCtx) (idx : Nat) (g : Expr) :
    Expr :=
  let ia := kc.comp.inners[idx]!
  mkAppN ia.app.getAppFn
    (ia.preArgs ++ #[kc.mc.corner] ++ cornerInnerArgsAt kc idx g)

/-- Corner-side args of inner app `idx` at a gadget value. -/
partial def cornerInnerArgsAt (kc : KnotCtx) (idx : Nat) (g : Expr) :
    Array Expr := Id.run do
  let ia := kc.comp.inners[idx]!
  let mut out := #[]
  for a in ia.args do
    match a with
    | .gadget => out := out.push g
    | .expr e => out := out.push e
    | .inner j => out := out.push (cornerInnerAt kc j g)
  pure out

end

/-- Explicit arguments of const `c` among `args` (its leading
binders). -/
def explicitOnly (c : Name) (args : Array Expr) :
    TermElabM (Array Expr) := do
  let info ← getConstInfo c
  forallBoundedTelescope info.type (some args.size) fun xs _ => do
    let mut out := #[]
    for x in xs, a in args do
      if (← x.fvarId!.getBinderInfo).isExplicit then
        out := out.push a
    pure out

/-- Apply a generated module lemma whose binder convention is
`ctxArgs ++ {pacing Tc Td hjT} ++ args (++ extra)` at explicit args
drawn from an applied occurrence of module `lemOwner`. -/
def applyModLemma (lemOwner : Name) (lem : Name)
    (pacing Tc Td hjT : Expr) (pre : Array Expr) (args : Array Expr)
    (extra : Array Expr := #[]) : TermElabM Expr := do
  let explicitPre ← explicitOnly lemOwner pre
  applyNamed lem pacing Tc Td hjT (explicitPre ++ args ++ extra)

/-! ## The derived-decision composition (`vdec` at the knot wires) -/

/-- The body module's choice-`vdec` applied at the knot's machine
wires, with the loop position at `gadgetMach` (the machine knot for
naming statements; the named diagonal for `wf` facts). -/
def vdecCompOf (kc : KnotCtx) (gadgetMach : Expr) : TermElabM Expr := do
  let some vd := kc.comp.gi.vdec? |
    throwError "HydroGen: body module {kc.comp.bodyMod} has no vdec"
  let bv := BVal.machine kc gadgetMach
  let mut plains := #[]
  let mut outers := #[]
  for a in kc.comp.args, k in kc.comp.kinds do
    match k with
    | .plain => plains := plains.push (← bargVal kc bv a k)
    | .wire _ => outers := outers.push (← bargVal kc bv a k)
    | .primDec f =>
      if f.schedPass && !f.isContent then
        outers := outers.push (← bargVal kc bv a k)
    | .decRec _ =>
      let e ← match a with
        | .expr e => pure e
        | _ => throwError "HydroGen: decision-record body arg is not \
            a plain expression"
      for (path, f) in flattenTree (← decFieldTreeOf kc.mc.corner e) do
        if f.schedPass && !f.isContent then
          outers := outers.push (← applyFieldPath e path)
  let explicitPre ← explicitOnly kc.comp.bodyMod kc.comp.preArgs
  applyNamed vd kc.mc.pacing kc.mc.Tc kc.mc.Td kc.mc.hjT
    (explicitPre ++ plains ++ outers)

/-! ## Knot namings -/

/-- Rule names for the machine naming: the body leg's sr lemma plus
every inner knot's sr naming. -/
def knotSrRules (kc : KnotCtx) : TermElabM (Array Name) := do
  let bodySrs := kc.comp.gi.srLemmas
  unless kc.comp.legIdx < bodySrs.size do
    throwError "HydroGen: {kc.comp.bodyMod} has no sr naming for leg \
      {kc.comp.legIdx}"
  let mut out := #[bodySrs[kc.comp.legIdx]!]
  for ia in kc.comp.inners do
    out := out ++ ia.gi.srLemmas
  pure out

def knotRrRules (kc : KnotCtx) : TermElabM (Array Name) := do
  let bodyRrs := kc.comp.gi.rrLemmas
  unless kc.comp.legIdx < bodyRrs.size do
    throwError "HydroGen: {kc.comp.bodyMod} has no rr naming for leg \
      {kc.comp.legIdx}"
  let mut out := #[bodyRrs[kc.comp.legIdx]!]
  for ia in kc.comp.inners do
    out := out ++ ia.gi.rrLemmas ++ ia.gi.srLemmas
  pure out

def namesList (ns : Array Name) : String :=
  String.intercalate ", " (ns.toList.map toString)

/-- Defeq coercion with a check (pins gadget constructors' implicit
`ord`/`ret` via the target carrier type). -/
def coerceTo (e : Expr) (ty : Expr) : TermElabM Expr := do
  unless ← isDefEq (← inferType e) ty do
    throwError "HydroGen: gadget coercion failed: {e} : {ty}"
  instantiateMVars e

/-- Embed a machine wire value as a corner wire (`schedC`), at the
given corner carrier type. -/
def cornerize (kc : KnotCtx) (m : Expr) (cornerTy : Expr) :
    TermElabM Expr := do
  let isTick := (← whnf cornerTy).isAppOf ``CoTickSing
  let c := if isTick then ``CoTickSing.schedC else ``CoStream.schedC
  coerceTo (← applyNamed c kc.mc.pacing kc.mc.Tc kc.mc.Td kc.mc.hjT
    #[m]) cornerTy

/-- The machine knot `K @ SchedSem` (statement RHS). -/
def knotKS (kc : KnotCtx) : TermElabM Expr := do
  pure <| mkAppN (mkConst kc.mc.mName)
    (kc.mc.ctxArgs ++ #[kc.mc.sched] ++ (← kc.mc.srArgs))

/-- `K_co_sr₁`: the machine naming, by the `co_knot_sr` house script. -/
def genKnotSr (kc : KnotCtx) : TermElabM Name := do
  let mc := kc.mc
  let lhs ← mkProjection mc.appCorner `sr
  let rhs ← knotKS kc
  let stmt ← mkForallFVars mc.allBinders (← mkEq lhs rhs)
  let defs := namesList (#[mc.mName] ++ kc.comp.unfolded)
  let rules := namesList (← knotSrRules kc)
  let name := mc.mName.appendAfter "_co_sr₁"
  addThmByTac name stmt s!"(intros; co_knot_sr [{defs}] [{rules}])"
  pure name

/-- `co_knot_rr` with fuel-pin closers (the choice-`vdec`'s fuel legs
are propositionally—not definitionally—`Td + 1`; the pins are
installed facts `PIN…` applied at `schedC`-cornerized outers, closing
the fuel leg by `exact`-defeq). -/
macro "co_knot_rr₂" hsr:term:max "[" defs:ident,* "]"
    "[" pins:term,* "]" "[" rules:term,* "]" : tactic => do
  let ds := defs.getElems
  let fuelAlts ← pins.getElems.mapM fun p =>
    `(tactic| exact Eq.symm $p)
  let fuelBase : Array (TSyntax `tactic) :=
    #[← `(tactic| with_reducible rfl), ← `(tactic| rfl)]
  let failT ← `(tactic| fail "co_knot_rr₂: fuel leg not closed")
  let fuelTac ← (fuelBase ++ fuelAlts).foldrM (init := failT)
    fun t acc => `(tactic| first | $t:tactic | $acc:tactic)
  `(tactic| (
    have h := $hsr
    unfold $[$ds]* at h ⊢
    first
      | rw [co_hfix_stream_sr] at h
      | rw [co_hfix_tick_sr] at h
    first
      | refine Eq.trans ?_ (values_hfix_stream' _ _ _).symm
      | refine Eq.trans ?_ (values_hfix_tick' _ _ _).symm
    first
      | rw [co_hfix_stream_rr]
      | rw [co_hfix_tick_rr]
    refine congrArg₂ _ ?_ ?_
    · $fuelTac:tactic
    funext v
    rw [h]
    co_body_rw [$rules,*]
    try simp only [co_schedC_sr, co_tick_schedC_sr]
    try with_reducible rfl
    try exact rfl))

/-- The `Values`-side argument list of `K` (wires `.rr`, the decision
unit at the composed `vdec`, fuels at `Td + 1`). -/
def knotRrArgs (kc : KnotCtx) (vdecC : Expr) : TermElabM (Array Expr) := do
  let mc := kc.mc
  let mut out := #[]
  for a in mc.args, k in mc.kinds do
    match k with
    | .wire _ => out := out.push (← mkProjection a `rr)
    | .decRec _ => out := out.push vdecC
    | .primDec .fixd =>
      out := out.push (← mkAppM ``HAdd.hAdd #[mc.Td, mkNatLit 1])
    | .primDec f =>
      if f.isContent then out := out.push vdecC
      else if f.valuesPass then out := out.push a
      else out := out.push (mkConst ``Unit.unit)
    | .plain => out := out.push a
  pure out

/-- `K_co_rr₁`: the denotational naming at the composed `vdec`. -/
def genKnotRr (kc : KnotCtx) (srName : Name) : TermElabM Name := do
  let mc := kc.mc
  let lhs ← mkProjection mc.appCorner `rr
  let KS ← knotKS kc
  let vdecC ← vdecCompOf kc KS
  let rhs := mkAppN (mkConst mc.mName)
    (mc.ctxArgs ++ #[mc.values] ++ (← knotRrArgs kc vdecC))
  let concl ← mkEq lhs rhs
  let defs := namesList (#[mc.mName] ++ kc.comp.unfolded)
  let rules := namesList (← knotRrRules kc)
  let hsrTerm := mkAppN (mkConst srName) mc.allBinders
  -- the fuel-pin facts, at `schedC`-cornerized outers (their machine
  -- legs are `exact`-defeq to the statement's raw machine values)
  let bvM := BVal.machine kc KS
  let mut pinArgs : Array Expr := #[]
  for a in kc.comp.args, k in kc.comp.kinds do
    match a with
    | .gadget => pinArgs := pinArgs.push (← cornerize kc KS kc.loopTy)
    | .expr e => pinArgs := pinArgs.push e
    | .inner idx =>
      let m ← bargVal kc bvM a k
      let ty ← inferType (kc.comp.inners[idx]!).app
      pinArgs := pinArgs.push (← cornerize kc m ty)
  let mut pinFacts : Array Expr := #[]
  for pin in kc.comp.gi.pinLemmas do
    pinFacts := pinFacts.push (← applyModLemma kc.comp.bodyMod pin
      mc.pacing mc.Tc mc.Td mc.hjT kc.comp.preArgs pinArgs)
  let pinNames := (Array.range pinFacts.size).map fun i =>
    Name.mkSimple s!"PIN{i + 1}"
  let pinList := String.intercalate ", "
    (pinNames.toList.map toString)
  let mut factDecls : Array (Name × BinderInfo ×
      (Array Expr → TermElabM Expr)) := #[]
  factDecls := factDecls.push (`HSR, .default,
    fun _ => inferType hsrTerm)
  for n in pinNames, f in pinFacts do
    factDecls := factDecls.push (n, .default, fun _ => inferType f)
  let prfClosed ← withLocalDecls factDecls fun factFVars => do
    let prf ← proveByTacOpen concl
      s!"(co_knot_rr₂ HSR [{defs}] [{pinList}] [{rules}])"
    pure ((← mkLambdaFVars factFVars prf).beta (#[hsrTerm] ++ pinFacts))
  let name := mc.mName.appendAfter "_co_rr₁"
  let stmt ← mkForallFVars mc.allBinders concl
  let val ← mkLambdaFVars mc.allBinders prfClosed
  addThm name stmt val
  pure name


/-! ## Knot causality (`causal_fix_*` over the composed body) -/

/-- Corner-side body args at a given gadget value (reduced exprs,
inner apps rebuilt at the corner). -/
def cornerArgsAt (kc : KnotCtx) (g : Expr) : Array Expr := Id.run do
  let mut out := #[]
  for a in kc.comp.args do
    match a with
    | .gadget => out := out.push g
    | .expr e => out := out.push e
    | .inner idx => out := out.push (cornerInnerAt kc idx g)
  pure out

/-- The knot-arg index of a raw body-argument expr. -/
def argIdxOf (kc : KnotCtx) (e : Expr) : TermElabM Nat := do
  let some i := kc.mc.args.idxOf? e |
    throwError "HydroGen: body arg {e} is not a knot binder"
  pure i

/-- The composed machine-side causality: the body leg's causal lemma
with `hxy` at the loop position, caller-supplied agreements at context
wires, and inner knots' `K_causal₁` recursively. Machine decision and
plain values are resolved by knot-arg index. -/
partial def composedCausal (kc : KnotCtx) (hxy : Expr)
    (wireAgree : Nat → TermElabM Expr)
    (decVal : Nat → TermElabM Expr)
    (plainVal : Nat → TermElabM Expr) : TermElabM Expr := do
  let bodyCausals := kc.comp.gi.causalLemmas
  unless kc.comp.legIdx < bodyCausals.size do
    throwError "HydroGen: {kc.comp.bodyMod} has no causality for leg \
      {kc.comp.legIdx}"
  go kc.comp.bodyMod bodyCausals[kc.comp.legIdx]! kc.comp.preArgs
    kc.comp.args kc.comp.kinds
where
  go (owner : Name) (lem : Name) (pre : Array Expr) (args : Array BArg)
      (kinds : Array ArgKind) : TermElabM Expr := do
    let mut queue := #[]
    for a in args, k in kinds do
      match k with
      | .wire _ => pure ()
      | .primDec _ | .decRec _ =>
        let e ← match a with
          | .expr e => decVal (← argIdxOf kc e)
          | _ => throwError "HydroGen: causal: decision at loop position"
        queue := queue.push e
      | .plain =>
        match a with
        | .expr e => queue := queue.push (← plainVal (← argIdxOf kc e))
        | _ => throwError "HydroGen: causal: plain at loop position"
    let mut hyps := #[]
    for a in args, k in kinds do
      if let .wire _ := k then
        match a with
        | .gadget => hyps := hyps.push hxy
        | .expr e => hyps := hyps.push (← wireAgree (← argIdxOf kc e))
        | .inner idx =>
          let ia := kc.comp.inners[idx]!
          unless ia.gi.causalLemmas.size ≥ 1 do
            throwError "HydroGen: inner knot {ia.kName} has no causality"
          hyps := hyps.push (← go ia.kName ia.gi.causalLemmas[0]!
            ia.preArgs ia.args ia.kinds)
    let explicitPre ← explicitOnly owner pre
    mkAppM lem (explicitPre ++ queue ++ hyps)

/-- `K_causal₁`: step causality of the machine knot. -/
def genKnotCausal (kc : KnotCtx) : TermElabM Name := do
  let mc := kc.mc
  withLocalDecl `h .implicit (mkConst ``Nat) fun hvar => do
  let mut decls : Array (Nat × Name × BinderInfo × Expr) := #[]
  for i in [0:mc.args.size] do
    let ty := reinterp mc.corner mc.sched (← inferType mc.args[i]!)
    let nm ← mc.args[i]!.fvarId!.getUserName
    match mc.kinds[i]! with
    | .wire _ =>
      decls := decls.push (i, nm, .implicit, ty)
      decls := decls.push (i, nm.appendAfter "'", .implicit, ty)
    | .plain => pure ()
    | _ => decls := decls.push (i, nm, .default, ty)
  withLocalDecls (decls.map fun (_, n, bi, ty) =>
      (n, bi, fun _ => pure ty)) fun xs => do
  let mut fstOf : Std.HashMap Nat Expr := {}
  let mut sndOf : Std.HashMap Nat Expr := {}
  let mut j := 0
  for i in [0:mc.args.size] do
    match mc.kinds[i]! with
    | .wire _ =>
      fstOf := fstOf.insert i xs[j]!
      sndOf := sndOf.insert i xs[j+1]!
      j := j + 2
    | .plain =>
      fstOf := fstOf.insert i mc.args[i]!
      sndOf := sndOf.insert i mc.args[i]!
    | _ =>
      fstOf := fstOf.insert i xs[j]!
      sndOf := sndOf.insert i xs[j]!
      j := j + 1
  let mut argBinders : Array Expr := #[]
  for i in [0:mc.args.size] do
    match mc.kinds[i]! with
    | .wire _ =>
      argBinders := argBinders.push (fstOf.get? i).get!
      argBinders := argBinders.push (sndOf.get? i).get!
    | .plain => argBinders := argBinders.push mc.args[i]!
    | _ => argBinders := argBinders.push (fstOf.get? i).get!
  let mut hypDecls : Array (Nat × Name × Expr) := #[]
  for i in [0:mc.args.size] do
    if let .wire cf := mc.kinds[i]! then
      let rel ← mkAppM (agreeRelOf cf)
        #[hvar, (fstOf.get? i).get!, (sndOf.get? i).get!]
      hypDecls := hypDecls.push (i, Name.mkSimple s!"ha{i}", rel)
  withLocalDecls (hypDecls.map fun (_, n, ty) =>
      (n, .default, fun _ => pure ty)) fun hyps => do
  let haOf : Std.HashMap Nat Expr := Id.run do
    let mut m := {}
    for d in hypDecls, hp in hyps do
      m := m.insert d.1 hp
    pure m
  let sideArgs := fun (side : Std.HashMap Nat Expr) => do
    let mut out := #[]
    for i in [0:mc.args.size] do
      out := out.push ((side.get? i).get!)
    pure out
  let lhsApp := mkAppN (mkConst mc.mName)
    (mc.ctxArgs ++ #[mc.sched] ++ (← sideArgs fstOf))
  let rhsApp := mkAppN (mkConst mc.mName)
    (mc.ctxArgs ++ #[mc.sched] ++ (← sideArgs sndOf))
  let cf ← match mc.legTys[0]!.getAppFn with
    | .const n _ =>
      match carrierFamOfHead n with
      | some cf => pure cf
      | none => throwError "HydroGen: knot leg is not a carrier"
    | _ => throwError "HydroGen: knot leg head"
  let concl ← mkAppM (agreeRelOf cf) #[hvar, lhsApp, rhsApp]
  let fFCK ← withLocalDecl `h' .default (mkConst ``Nat) fun h'E => do
    withLocalDecl `hh' .default (← mkAppM ``Nat.le #[h'E, hvar])
        fun hh'E => do
    let machLoopTy := reinterp mc.corner mc.sched kc.loopTy
    withLocalDecl `x .default machLoopTy fun xE => do
    withLocalDecl `y .default machLoopTy fun yE => do
    withLocalDecl `hxy .default
        (← mkAppM kc.gad.agree #[h'E, xE, yE]) fun hxyE => do
    let prf ← composedCausal kc hxyE
      (fun i => do
        let cfI ← match mc.kinds[i]! with
          | .wire c => pure c
          | _ => throwError "HydroGen: not a wire"
        mkAppM (agreeRelOf cfI ++ `mono) #[hh'E, (haOf.get? i).get!])
      (fun i => pure (fstOf.get? i).get!)
      (fun i => pure mc.args[i]!)
    mkLambdaFVars #[h'E, hh'E, xE, yE, hxyE] prf
  let factTy ← inferType fFCK
  let prfClosed ← withLocalDecl `FCK .default factTy fun fckF => do
    let defs := namesList (#[mc.mName] ++ kc.comp.unfolded)
    let fixRw := if kc.gad.isTick then "sched_hfix_tick'"
      else "sched_hfix_stream'"
    let fixCausal := if kc.gad.isTick then "causal_fix_tick"
      else "causal_fix_stream"
    let prf ← proveByTacOpen concl
      (s!"(simp only [{defs}]; rw [{fixRw}, {fixRw}]; " ++
       s!"refine {fixCausal} _ ?_; intro h' hh' x y hxy; " ++
       "exact FCK h' hh' x y hxy)")
    pure ((← mkLambdaFVars #[fckF] prf).beta #[fFCK])
  let binders := mc.ctxArgs ++ #[mc.pacing, hvar] ++ argBinders ++ hyps
  let name := mc.mName.appendAfter "_causal₁"
  let stmt ← mkForallFVars binders concl
  let val ← mkLambdaFVars binders prfClosed
  addThm name stmt val
  pure name

/-! ## Knot `Values` monotonicity (`iterate_mono_param` composition) -/

/-- Reflexivity of the `Values`-side order at a wire value. -/
def valuesRelRefl (cf : CarrierFam) (ty : Expr) (w : Expr) :
    TermElabM Expr := do
  withLocalDecl `i .default (← pure (← whnf (← inferType w)).bindingDomain!)
      fun iE => do
    let wi := mkApp w iE
    let prf ← match cf with
      | .stream => do
        let some tyW ← whnfUntil (← inferType wi) ``PoolCarrier |
          throwError "HydroGen: wire carrier is not a pool"
        let n := tyW.getAppNumArgs
        mkAppM ``PoolLe.refl
          #[tyW.getArg! (n - 2), tyW.getArg! (n - 1), wi]
      | .tickSing => do
        let bound ← whnfR (ty.getArg! (ty.getAppNumArgs - 1))
        if bound.isAppOf ``SingBound.monotonic then
          mkAppM ``List.prefix_refl #[← mkProjection wi `vals]
        else
          mkAppM ``List.prefix_refl #[wi]
      | _ => mkAppM ``List.prefix_refl #[wi]
    mkLambdaFVars #[iE] prf

/-- The composed `Values` monotonicity step: the body leg's mono lemma
with `hab` at the loop, caller-supplied order hypotheses at context
wires, decisions by `decVal`, inner knots' `K_mono₁` recursively. -/
partial def composedMono (kc : KnotCtx) (hab : Expr)
    (wireHyp : Nat → TermElabM Expr)
    (decVal : Nat → TermElabM Expr)
    (plainVal : Nat → TermElabM Expr) : TermElabM Expr := do
  let bodyMonos := kc.comp.gi.monoLemmas
  unless kc.comp.legIdx < bodyMonos.size do
    throwError "HydroGen: {kc.comp.bodyMod} has no monotonicity for \
      leg {kc.comp.legIdx}"
  go kc.comp.bodyMod bodyMonos[kc.comp.legIdx]! kc.comp.preArgs
    kc.comp.args kc.comp.kinds
where
  go (owner : Name) (lem : Name) (pre : Array Expr) (args : Array BArg)
      (kinds : Array ArgKind) : TermElabM Expr := do
    let mut queue := #[]
    for a in args, k in kinds do
      match k with
      | .wire _ => pure ()
      | .primDec _ | .decRec _ =>
        let e ← match a with
          | .expr e => decVal (← argIdxOf kc e)
          | _ => throwError "HydroGen: mono: decision at loop position"
        queue := queue.push e
      | .plain =>
        match a with
        | .expr e => queue := queue.push (← plainVal (← argIdxOf kc e))
        | _ => throwError "HydroGen: mono: plain at loop position"
    let mut hyps := #[]
    for a in args, k in kinds do
      if let .wire _ := k then
        match a with
        | .gadget => hyps := hyps.push hab
        | .expr e => hyps := hyps.push (← wireHyp (← argIdxOf kc e))
        | .inner idx =>
          let ia := kc.comp.inners[idx]!
          unless ia.gi.monoLemmas.size ≥ 1 do
            throwError "HydroGen: inner knot {ia.kName} has no \
              monotonicity"
          hyps := hyps.push (← go ia.kName ia.gi.monoLemmas[0]!
            ia.preArgs ia.args ia.kinds)
    let explicitPre ← explicitOnly owner pre
    mkAppM lem (explicitPre ++ queue ++ hyps)

/-- The fuel of the knot's `Values` fix, under a decision-argument
valuation (the `df` expr's projection path applied at the values-side
decision). -/
def knotFuelAt (kc : KnotCtx) (decVal : Nat → TermElabM Expr) :
    TermElabM Expr := do
  let (op, path) ← peelOuterProj kc.df []
  let i ← argIdxOf kc op
  applyLeg (← decVal i) path

/-- `K_mono₁`: `Values` monotonicity of the denotational knot at a
generic decision. -/
def genKnotMono (kc : KnotCtx) : TermElabM Name := do
  let mc := kc.mc
  let mut decls : Array (Nat × Name × BinderInfo × Expr) := #[]
  for i in [0:mc.args.size] do
    let ty := reinterp mc.corner mc.values (← inferType mc.args[i]!)
    let nm ← mc.args[i]!.fvarId!.getUserName
    match mc.kinds[i]! with
    | .wire _ =>
      decls := decls.push (i, nm, .implicit, ty)
      decls := decls.push (i, nm.appendAfter "'", .implicit, ty)
    | .plain => pure ()
    | _ => decls := decls.push (i, nm, .default, ty)
  withLocalDecls (decls.map fun (_, n, bi, ty) =>
      (n, bi, fun _ => pure ty)) fun xs => do
  let mut fstOf : Std.HashMap Nat Expr := {}
  let mut sndOf : Std.HashMap Nat Expr := {}
  let mut j := 0
  for i in [0:mc.args.size] do
    match mc.kinds[i]! with
    | .wire _ =>
      fstOf := fstOf.insert i xs[j]!
      sndOf := sndOf.insert i xs[j+1]!
      j := j + 2
    | .plain =>
      fstOf := fstOf.insert i mc.args[i]!
      sndOf := sndOf.insert i mc.args[i]!
    | _ =>
      fstOf := fstOf.insert i xs[j]!
      sndOf := sndOf.insert i xs[j]!
      j := j + 1
  let mut argBinders : Array Expr := #[]
  for i in [0:mc.args.size] do
    match mc.kinds[i]! with
    | .wire _ =>
      argBinders := argBinders.push (fstOf.get? i).get!
      argBinders := argBinders.push (sndOf.get? i).get!
    | .plain => argBinders := argBinders.push mc.args[i]!
    | _ => argBinders := argBinders.push (fstOf.get? i).get!
  let mut hypDecls : Array (Nat × Name × Expr) := #[]
  for i in [0:mc.args.size] do
    if let .wire cf := mc.kinds[i]! then
      let ty := reinterp mc.corner mc.values (← inferType mc.args[i]!)
      let rel ← valuesRelOf cf ty (fstOf.get? i).get! (sndOf.get? i).get!
      hypDecls := hypDecls.push (i, Name.mkSimple s!"hm{i}", rel)
  withLocalDecls (hypDecls.map fun (_, n, ty) =>
      (n, .default, fun _ => pure ty)) fun hyps => do
  let hmOf : Std.HashMap Nat Expr := Id.run do
    let mut m := {}
    for d in hypDecls, hp in hyps do
      m := m.insert d.1 hp
    pure m
  let sideArgs := fun (side : Std.HashMap Nat Expr) => do
    let mut out := #[]
    for i in [0:mc.args.size] do
      out := out.push ((side.get? i).get!)
    pure out
  let lhsApp := mkAppN (mkConst mc.mName)
    (mc.ctxArgs ++ #[mc.values] ++ (← sideArgs fstOf))
  let rhsApp := mkAppN (mkConst mc.mName)
    (mc.ctxArgs ++ #[mc.values] ++ (← sideArgs sndOf))
  let cf ← match mc.legTys[0]!.getAppFn with
    | .const n _ => pure (carrierFamOfHead n).get!
    | _ => throwError "HydroGen: knot leg head"
  let legTyV := reinterp mc.corner mc.values mc.legTys[0]!
  let concl ← valuesRelOf cf legTyV lhsApp rhsApp
  -- the loop's Values carrier and pointwise relation
  let domV := reinterp mc.corner mc.values kc.loopTy
  let iTy := (← whnf domV).bindingDomain!
  let mkRel ← withLocalDecl `a .default domV fun aE => do
    withLocalDecl `b .default domV fun bE => do
    let rel ← valuesRelOf cf domV aE bE
    mkLambdaFVars #[aE, bE] rel
  -- F / F' : the Values body at the two sides
  let valuesBodyAt := fun (side : Std.HashMap Nat Expr) (w : Expr) => do
    let bv : BVal :=
      { interp := mc.values, gadget := w,
        wire := fun e => do pure (side.get? (← argIdxOf kc e)).get!,
        prim := fun _ e => do pure (side.get? (← argIdxOf kc e)).get!,
        recd := fun e => do pure (side.get? (← argIdxOf kc e)).get! }
    let args ← bodyArgsVal kc bv
    let app := mkAppN (mkConst kc.comp.bodyMod)
      (kc.comp.preArgs ++ #[mc.values] ++ args)
    applyLeg app kc.comp.legPath
  let fF ← withLocalDecl `w .default domV fun wE => do
    mkLambdaFVars #[wE] (← valuesBodyAt fstOf wE)
  let fF' ← withLocalDecl `w .default domV fun wE => do
    mkLambdaFVars #[wE] (← valuesBodyAt sndOf wE)
  -- the step
  let hFF' ← withLocalDecl `a .implicit domV fun aE => do
    withLocalDecl `b .implicit domV fun bE => do
    withLocalDecl `hab .default ((mkRel.beta #[aE, bE]).headBeta)
        fun habE => do
    let prf ← composedMono kc habE
      (fun i => pure (hmOf.get? i).get!)
      (fun i => pure (fstOf.get? i).get!)
      (fun i => pure mc.args[i]!)
    mkLambdaFVars #[aE, bE, habE] prf
  let seed ← match cf with
    | .stream => do
      let some tyP ← whnfUntil ((← whnf domV).bindingBody!)
          ``PoolCarrier |
        throwError "HydroGen: loop carrier is not a pool"
      let n := tyP.getAppNumArgs
      withLocalDecl `i .default iTy fun iE => do
        mkLambdaFVars #[iE] (← mkAppOptM ``PoolBot
          #[some (tyP.getArg! 0), none, some (tyP.getArg! (n - 2)),
            some (tyP.getArg! (n - 1))])
    | _ => do
      let tr ← whnf ((← whnf domV).bindingBody!)
      withLocalDecl `i .default iTy fun iE => do
        mkLambdaFVars #[iE]
          (← mkAppOptM ``List.nil #[some (tr.getArg! 0)])
  let hx ← valuesRelRefl cf domV seed
  let fuel ← knotFuelAt kc (fun i => pure (fstOf.get? i).get!)
  let its ← mkAppOptM ``iterate_mono_param
    #[none, some mkRel, some fF, some fF', some hFF', some seed,
      some seed, some hx, some fuel]
  let prf ← mkExpectedTypeHint its concl
  let binders := mc.ctxArgs ++ argBinders ++ hyps
  let name := mc.mName.appendAfter "_mono₁"
  let stmt ← mkForallFVars binders concl
  let val ← mkLambdaFVars binders prf
  addThm name stmt val
  pure name


/-! ## The knot `wf` triple -/

/-- Recursive inner-knot `wf` at a (possibly lowered) valuation. -/
partial def innerWfAt (kc : KnotCtx) (idx : Nat) (bv : BVal)
    (TcE hjTE : Expr) (hwOf : Std.HashMap Nat Expr) :
    TermElabM Expr := do
  let ia := kc.comp.inners[idx]!
  unless ia.gi.wfLemmas.size ≥ 1 do
    throwError "HydroGen: inner knot {ia.kName} has no wf lemma"
  let mut args := #[]
  for a in ia.args, k in ia.kinds do
    args := args.push (← bargVal kc bv a k)
  let mut wfhyps : Array Expr := #[]
  for a in ia.args, k in ia.kinds do
    if let .wire _ := k then
      match a with
      | .gadget => wfhyps := wfhyps.push (Lean.mkConst ``True.intro)
      | .expr e =>
        wfhyps := wfhyps.push (hwOf.get? (← argIdxOf kc e)).get!
      | .inner j =>
        wfhyps := wfhyps.push (← innerWfAt kc j bv TcE hjTE hwOf)
  applyModLemma ia.kName ia.gi.wfLemmas[0]! kc.mc.pacing TcE kc.mc.Td
    hjTE ia.preArgs (args ++ wfhyps)

/-- `K_co_wf₁`: the corner `wf` triple, by the validated blueprint
with composition-aware facts. -/
def genKnotWf (kc : KnotCtx) : TermElabM Name := do
  let mc := kc.mc
  let gad := kc.gad
  let comp := kc.comp
  -- input-wf hypotheses for the knot's wire args
  let mut hypDecls : Array (Nat × Name × Expr) := #[]
  for i in [0:mc.args.size] do
    if let .wire _ := mc.kinds[i]! then
      hypDecls := hypDecls.push
        (i, Name.mkSimple s!"hw{i}", ← mkProjection mc.args[i]! `wf)
  withLocalDecls (hypDecls.map fun (_, n, ty) =>
      (n, BinderInfo.default, fun _ => pure ty)) fun hyps => do
  let hwOf : Std.HashMap Nat Expr := Id.run do
    let mut m := {}
    for d in hypDecls, hyp in hyps do
      m := m.insert d.1 hyp
    pure m
  let B := kc.B
  let vbodyB ← mkAppM gad.vbody #[B]
  let fixSrB ← mkAppM gad.fixSr #[B]
  let loopTy := kc.loopTy
  let domX := reinterp mc.corner mc.sched loopTy
  let domV := reinterp mc.corner mc.values loopTy
  let iTy := (← whnf domX).bindingDomain!
  -- lemma applications over the body composition
  let bodyLemAt := fun (lem : Name) (args : Array Expr) =>
    applyModLemma comp.bodyMod lem mc.pacing mc.Tc mc.Td mc.hjT
      comp.preArgs args
  let innerLemAt := fun (idx : Nat) (lem : Name) (args : Array Expr) =>
    applyModLemma (kc.comp.inners[idx]!).kName lem mc.pacing mc.Tc
      mc.Td mc.hjT (kc.comp.inners[idx]!).preArgs args
  let innerSrEqsAt := fun (g : Expr) => do
    let mut out := #[]
    for idx in [0:comp.inners.size] do
      let ia := comp.inners[idx]!
      out := out.push (← innerLemAt idx ia.gi.srLemmas[0]!
        (cornerInnerArgsAt kc idx g))
    pure out
  let innerRrEqsAt := fun (g : Expr) => do
    let mut out := #[]
    for idx in [0:comp.inners.size] do
      let ia := comp.inners[idx]!
      unless ia.gi.rrLemmas.size ≥ 1 do
        throwError "HydroGen: inner knot {ia.kName} has no rr naming"
      out := out.push (← innerLemAt idx ia.gi.rrLemmas[0]!
        (cornerInnerArgsAt kc idx g))
    pure out
  let schedCAt := fun (x : Expr) => do
    coerceTo (← applyNamed gad.schedC mc.pacing mc.Tc mc.Td mc.hjT #[x])
      loopTy
  let probeCAt := fun (x v : Expr) => do
    coerceTo (← applyNamed gad.probeC mc.pacing mc.Tc mc.Td mc.hjT
      #[x, v]) loopTy
  -- ===== FX =====
  let fFX ← withLocalDecl `x .default domX fun xE => do
    let g ← schedCAt xE
    let base ← bodyLemAt comp.gi.srLemmas[comp.legIdx]!
      (cornerArgsAt kc g)
    let fact ← collapseFact (← rwRhsAll base (← innerSrEqsAt g))
    mkLambdaFVars #[xE] fact
  -- ===== FC =====
  let fcDecVal : Nat → TermElabM Expr := fun i => do
    match mc.kinds[i]! with
    | .primDec f =>
      pure (if f.schedPass then mc.args[i]! else mkConst ``Unit.unit)
    | .decRec _ =>
      repackRec mc.corner mc.sched
        (fun f p =>
          pure (if f.schedPass then p else mkConst ``Unit.unit))
        mc.args[i]!
    | _ => pure mc.args[i]!
  let fFC ← withLocalDecl `h .default (mkConst ``Nat) fun hE => do
    withLocalDecl `x .default domX fun xE => do
    withLocalDecl `y .default domX fun yE => do
    withLocalDecl `hxy .default (← mkAppM gad.agree #[hE, xE, yE])
        fun hxyE => do
    let prf ← composedCausal kc hxyE
      (fun i => do
        let cfI ← match mc.kinds[i]! with
          | .wire c => pure c
          | _ => throwError "HydroGen: not a wire"
        mkAppM (agreeRelOf cfI ++ `refl)
          #[hE, ← mkProjection mc.args[i]! `sr])
      fcDecVal
      (fun i => pure mc.args[i]!)
    mkLambdaFVars #[hE, xE, yE, hxyE] prf
  -- ===== HVA =====
  let fHVA ← withLocalDecl `v .default domV fun vE => do
    let g ← probeCAt fixSrB vE
    let base ← bodyLemAt comp.gi.rrLemmas[comp.legIdx]!
      (cornerArgsAt kc g)
    let fact ← collapseFact (← rwRhsAll base
      ((← innerRrEqsAt g) ++ (← innerSrEqsAt g)))
    let rhs := (← inferType fact).appArg!
    let ty ← mkEq (mkApp vbodyB vE) rhs
    mkLambdaFVars #[vE] (← mkExpectedTypeHint fact ty)
  -- ===== FM =====
  let vdecFix ← vdecCompOf kc fixSrB
  let fmDecVal : Nat → TermElabM Expr := fun i => do
    match mc.kinds[i]! with
    | .primDec .fixd => mkAppM ``HAdd.hAdd #[mc.Td, mkNatLit 1]
    | .primDec f =>
      if f.isContent then pure vdecFix
      else if f.valuesPass then pure mc.args[i]!
      else pure (mkConst ``Unit.unit)
    | .decRec _ => pure vdecFix
    | _ => pure mc.args[i]!
  let mkRel2 := fun (p q : Expr) => do
    if gad.isTick then
      mkAppM ``List.IsPrefix #[p, q]
    else
      let some tyP ← whnfUntil (← inferType p) ``PoolCarrier |
        throwError "HydroGen: loop carrier is not a pool"
      let n := tyP.getAppNumArgs
      mkAppM ``PoolLe #[tyP.getArg! (n - 2), tyP.getArg! (n - 1), p, q]
  let relV ← withLocalDecl `a .default domV fun aE => do
    withLocalDecl `b .default domV fun bE => do
    withLocalDecl `j .default iTy fun jE => do
    mkLambdaFVars #[aE, bE]
      (← mkForallFVars #[jE] (← mkRel2 (mkApp aE jE) (mkApp bE jE)))
  let fFM ← withLocalDecl `a .default domV fun aE => do
    withLocalDecl `b .default domV fun bE => do
    withLocalDecl `hab .default ((relV.beta #[aE, bE]).headBeta)
        fun habE => do
    let prf ← composedMono kc habE
      (fun i => do
        let cfI ← match mc.kinds[i]! with
          | .wire c => pure c
          | _ => throwError "HydroGen: not a wire"
        let ty := reinterp mc.corner mc.values
          (← inferType mc.args[i]!)
        valuesRelRefl cfI ty (← mkProjection mc.args[i]! `rr))
      fmDecVal
      (fun i => pure mc.args[i]!)
    mkLambdaFVars #[aE, bE, habE] prf
  -- ===== FH =====
  let seedV ← if gad.isTick then do
      let tr ← whnf ((← whnf domV).bindingBody!)
      withLocalDecl `i .default iTy fun iE => do
        mkLambdaFVars #[iE]
          (← mkAppOptM ``List.nil #[some (tr.getArg! 0)])
    else do
      let some tyP ← whnfUntil ((← whnf domV).bindingBody!)
          ``PoolCarrier |
        throwError "HydroGen: loop carrier is not a pool"
      let n := tyP.getAppNumArgs
      withLocalDecl `i .default iTy fun iE => do
        mkLambdaFVars #[iE] (← mkAppOptM ``PoolBot
          #[some (tyP.getArg! 0), none, some (tyP.getArg! (n - 2)),
            some (tyP.getArg! (n - 1))])
  let fFH ← do
    let hx ← withLocalDecl `j .default iTy fun jE => do
      let prf ← if gad.isTick then
          mkAppOptM ``List.nil_prefix
            #[none, some (mkApp (mkApp vbodyB seedV) jE)]
        else do
          let some tyP ← whnfUntil ((← whnf domV).bindingBody!)
              ``PoolCarrier | throwError "HydroGen: pool"
          let n := tyP.getAppNumArgs
          mkAppM ``poolBot_le #[tyP.getArg! (n - 2),
            tyP.getArg! (n - 1), mkApp (mkApp vbodyB seedV) jE]
      mkLambdaFVars #[jE] prf
    let hF ← withLocalDecl `a .implicit domV fun aE => do
      withLocalDecl `b .implicit domV fun bE => do
      let relab := (relV.beta #[aE, bE]).headBeta
      withLocalDecl `hab .default relab fun habE => do
      withLocalDecl `j .default iTy fun jE => do
      let hvaA := mkApp fHVA aE
      let hvaB := mkApp fHVA bE
      let cfA ← mkAppM ``congrFun #[hvaA, jE]
      let cfB ← mkAppM ``congrFun #[hvaB, jE]
      let elemTy := (← whnf domV).bindingBody!
      let pl2 ← withLocalDecl `p .default elemTy fun pE => do
        withLocalDecl `q .default elemTy fun qE => do
        mkLambdaFVars #[pE, qE] (← mkRel2 pE qE)
      let eq2 ← mkAppM ``congrArg₂ #[pl2, cfA, cfB]
      let mono := mkApp (mkApp (mkApp fFM aE) bE) habE
      let inner ← mkAppM ``Eq.mpr #[eq2, mkApp mono jE]
      mkLambdaFVars #[aE, bE, habE, jE] inner
    withLocalDecl `m .default (mkConst ``Nat) fun mE => do
    withLocalDecl `i .default iTy fun iE => do
    let its ← mkAppOptM ``iterate_le_succ
      #[none, some relV, none, some seedV, some hx, some hF]
    mkLambdaFVars #[mE, iE] (mkApp (mkApp its mE) iE)
  -- ===== the lowered instance (hcplj) =====
  let cornerAt := fun (TcE hjTE : Expr) =>
    mkAppN (mkConst ``CoupleSem)
      #[mc.L, mc.memE, mc.pacing, TcE, mc.Td, hjTE]
  let cpljTele := fun (k : Expr → Expr → Expr → Expr → Expr →
      TermElabM Expr) => do
    withLocalDecl `j .default (mkConst ``Nat) fun jE => do
    withLocalDecl `hj .default (← mkAppM ``Nat.le #[jE, mc.Tc]) fun hjE => do
    withLocalDecl `x .default domX fun xE => do
    withLocalDecl `v .default domV fun vE => do
    let hxvTy ← withLocalDecl `t .default (mkConst ``Nat) fun tE => do
      withLocalDecl `ht .default (← mkAppM ``Nat.le #[tE, jE]) fun htE => do
      withLocalDecl `i .default iTy fun iE => do
      let body ← if gad.isTick then
          mkAppM ``List.IsPrefix
            #[mkApp (mkApp xE iE) tE, mkApp vE iE]
        else do
          let view ← mkAppM ``StepHist.view #[mkApp xE iE, tE]
          let some tyV ← whnfUntil (← inferType (mkApp vE iE))
              ``PoolCarrier |
            throwError "HydroGen: loop reader carrier is not a pool"
          let n := tyV.getAppNumArgs
          mkAppM ``ListLe
            #[tyV.getArg! (n - 2), tyV.getArg! (n - 1), view,
              mkApp vE iE]
      mkForallFVars #[tE, htE, iE] body
    withLocalDecl `hxv .default hxvTy fun hxvE => do
    let body ← k jE hjE xE vE hxvE
    mkLambdaFVars #[jE, hjE, xE, vE, hxvE] body
  let mkLowVal := fun (jE hjE xE vE hxvE : Expr) => do
    let hjT' ← mkAppM ``Nat.le_trans #[hjE, mc.hjT]
    let corner' := cornerAt jE hjT'
    let mkCArg ← do
      if gad.isTick then
        coerceTo (← applyNamed gad.mkC mc.pacing jE mc.Td hjT'
          #[xE, vE, hxvE]) (reinterp mc.corner corner' loopTy)
      else do
        let hc ← withLocalDecl `i' .default iTy fun iE => do
          mkLambdaFVars #[iE]
            (mkApp (mkApp (mkApp hxvE jE) (← mkAppM ``Nat.le_refl #[jE]))
              iE)
        coerceTo (← applyNamed gad.mkC mc.pacing jE mc.Td hjT'
          #[xE, vE, hc]) (reinterp mc.corner corner' loopTy)
    let bv : BVal :=
      { interp := corner', gadget := mkCArg,
        wire := fun e => do
          let lc := if (← whnf (← inferType e)).isAppOf ``CoTickSing
            then ``CoTickSing.lowerC else ``CoStream.lowerC
          coerceTo (← applyNamed lc mc.pacing mc.Tc mc.Td mc.hjT
            #[hjE, hjT', e])
            (reinterp mc.corner corner' (← inferType e)),
        prim := fun _ e => pure e,
        recd := fun e =>
          repackRec mc.corner corner' (fun _ p => pure p) e }
    pure (bv, hjT')
  let innerEqsLow := fun (bv : BVal) (jE hjT' : Expr) (rr : Bool) => do
    let mut out := #[]
    for idx in [0:comp.inners.size] do
      let ia := comp.inners[idx]!
      let mut args := #[]
      for a in ia.args, k in ia.kinds do
        args := args.push (← bargVal kc bv a k)
      let lem := if rr then ia.gi.rrLemmas[0]! else ia.gi.srLemmas[0]!
      out := out.push (← applyModLemma ia.kName lem mc.pacing jE mc.Td
        hjT' ia.preArgs args)
    pure out
  let fFOUT ← cpljTele fun jE hjE xE vE hxvE => do
    let (bv, hjT') ← mkLowVal jE hjE xE vE hxvE
    let args ← bodyArgsVal kc bv
    let mut wfExtras : Array Expr := #[]
    for a in comp.args, k in comp.kinds do
      if let .wire _ := k then
        match a with
        | .gadget => wfExtras := wfExtras.push (Lean.mkConst ``True.intro)
        | .expr e =>
          wfExtras := wfExtras.push (hwOf.get? (← argIdxOf kc e)).get!
        | .inner idx =>
          wfExtras := wfExtras.push (← innerWfAt kc idx bv jE hjT' hwOf)
    unless comp.gi.wfLemmas.size > comp.legIdx do
      throwError "HydroGen: {comp.bodyMod} has no wf lemma for the leg"
    let wfApp ← applyModLemma comp.bodyMod
      comp.gi.wfLemmas[comp.legIdx]! mc.pacing jE mc.Td hjT'
      comp.preArgs (args ++ wfExtras)
    let modApp := (← inferType wfApp).appArg!
    let cplPrj ← mkProjection modApp `cpl
    if gad.isTick then
      pure (mkApp (mkApp (mkApp cplPrj wfApp) jE)
        (← mkAppM ``Nat.le_refl #[jE]))
    else
      pure (mkApp cplPrj wfApp)
  let fFSR ← cpljTele fun jE hjE xE vE hxvE => do
    let (bv, hjT') ← mkLowVal jE hjE xE vE hxvE
    let e1 ← applyModLemma comp.bodyMod
      comp.gi.srLemmas[comp.legIdx]! mc.pacing jE mc.Td hjT'
      comp.preArgs (← bodyArgsVal kc bv)
    let e1' ← collapseFact (← rwRhsAll e1
      (← innerEqsLow bv jE hjT' false))
    let g ← schedCAt xE
    let e2 ← bodyLemAt comp.gi.srLemmas[comp.legIdx]!
      (cornerArgsAt kc g)
    let e2' ← collapseFact (← rwRhsAll e2 (← innerSrEqsAt g))
    mkAppM ``Eq.trans #[e1', ← mkAppM ``Eq.symm #[e2']]
  let fFRR ← cpljTele fun jE hjE xE vE hxvE => do
    let (bv, hjT') ← mkLowVal jE hjE xE vE hxvE
    let e1 ← applyModLemma comp.bodyMod
      comp.gi.rrLemmas[comp.legIdx]! mc.pacing jE mc.Td hjT'
      comp.preArgs (← bodyArgsVal kc bv)
    let e1' ← collapseFact (← rwRhsAll e1
      ((← innerEqsLow bv jE hjT' true) ++
       (← innerEqsLow bv jE hjT' false)))
    let g ← probeCAt xE vE
    let e2 ← bodyLemAt comp.gi.rrLemmas[comp.legIdx]!
      (cornerArgsAt kc g)
    let e2' ← collapseFact (← rwRhsAll e2
      ((← innerRrEqsAt g) ++ (← innerSrEqsAt g)))
    mkAppM ``Eq.trans #[e1', ← mkAppM ``Eq.symm #[e2']]
  -- ===== install the facts and run the fixed script =====
  let facts := #[fFX, fFC, fHVA, fFM, fFH, fFOUT, fFSR, fFRR]
  let factNames : Array Name :=
    #[`FX, `FC, `HVA, `FM, `FH, `FOUT, `FSR, `FRR]
  let mut factTys := #[]
  for f in facts do
    factTys := factTys.push (← inferType f)
  let factTysA := factTys
  withLocalDecls
      ((factNames.zip factTysA).map fun (n, ty) =>
        (n, BinderInfo.default, fun _ => pure ty)) fun factFVars => do
  let concl ← mkProjection mc.appCorner `wf
  let script :=
    s!"(co_wf_simp [{mc.mName}]; refine ⟨?_, ?_, ?_⟩; " ++
    "(intro h x y hxy; have h1 := FC h x y hxy; " ++
    "rw [← FX x, ← FX y] at h1; exact h1); " ++
    "(exact FH); " ++
    "(intro j hj x v hxv i; have h1 := FOUT j hj x v hxv i; " ++
    "rw [FSR j hj x v hxv, FRR j hj x v hxv] at h1; exact h1))"
  let prf ← proveByTacOpen concl script
  let prfClosed := (← mkLambdaFVars factFVars prf).beta facts
  let name := mc.mName.appendAfter "_co_wf₁"
  let stmt ← mkForallFVars (mc.allBinders ++ hyps) concl
  let val ← mkLambdaFVars (mc.allBinders ++ hyps) prfClosed
  addThm name stmt val
  pure name

/-! ## The command -/

elab "hydro_knot " M:ident ids:(hydroGenIds)? : command => do
  let mName ← liftCoreM <| realizeGlobalConstNoOverload M
  let extras ← elabExtras (ids.map (·.raw))
  let extras := extrasWithSpec (← getEnv) mName extras
  let (sr, rr, ca, mo, wf) ← liftTermElabM <|
    withModCtx mName (extras := extras) fun mc =>
    withKnotCtx mc fun kc => do
      let sr ← genKnotSr kc
      logInfo m!"hydro_knot {mName}: sr ok"
      let rr ← genKnotRr kc sr
      logInfo m!"hydro_knot {mName}: rr ok"
      let ca ← genKnotCausal kc
      logInfo m!"hydro_knot {mName}: causal ok"
      let mo ← genKnotMono kc
      logInfo m!"hydro_knot {mName}: mono ok"
      let wf ← genKnotWf kc
      pure (sr, rr, ca, mo, wf)
  registerInfo mName fun gi =>
    { gi with srLemmas := #[sr], rrLemmas := #[rr],
              causalLemmas := #[ca], monoLemmas := #[mo],
              wfLemmas := #[wf], isKnot := true }
  logInfo m!"hydro_knot {mName}: {sr}, {rr}, {ca}, {mo}, {wf}"

/-! ## Glue modules (`hydro_glue`)

Modules whose content decisions are consumed entirely by registered
callees (`leader_election` passes its whole record to the knots;
`pcBody` slices `dec'.le`/`dec'.sp` into `leader_election` and
`sequence_payload`). Their namings are generated by **simp
discovery**: the corner body is rewritten ONCE by the callee namings
(+ the gadget collapses), the emergent `Values`-side decision record
is extracted and named (`M_vdec`, in the `genRrEx` binder
convention), and the theorem closes with a single module-scale defeq
hint — no `∃`-witness goals and no re-simping loops (the 7 GB
lesson). -/

/-- Structurally zeta-reduce all `let`/`letFun` (`have`) bindings —
glue bodies chain `have le := (callee …) …; …` and a projection on
the chain blocks `simp`'s own reduction. Definitionally transparent
(the kernel pays one beta per binding). -/
partial def zetaAll (e : Expr) : CoreM Expr :=
  Core.transform e (post := fun e => do
    match e with
    | .letE _ _ v b _ => return .visit (b.instantiate1 v)
    | _ =>
      if e.isAppOf ``letFun && e.getAppNumArgs ≥ 4 then
        let args := e.getAppArgs
        return .visit (mkAppN (args[3]!.beta #[args[2]!]) args[4:args.size])
      else
        return .continue)

/-- The `co_simp` projection set as data (keep in sync with the
`co_simp` macro in `CoupleProj` — the glue meet check fails loudly on
drift): pushes `rr`/`sr` through every op. -/
def coSimpBase : Array Name := #[
  ``co_input_rr, ``co_input_sr, ``co_tick_input_rr, ``co_tick_input_sr,
  ``co_probeC_rr, ``co_probeC_sr, ``co_tick_probeC_rr, ``co_tick_probeC_sr,
  ``co_mkC_rr, ``co_mkC_sr, ``co_tick_mkC_rr, ``co_tick_mkC_sr,
  ``co_mkC_rr_raw, ``co_mkC_sr_raw,
  ``co_tick_mkC_rr_raw, ``co_tick_mkC_sr_raw,
  ``co_embedS_sr_raw, ``co_tick_embedS_sr_raw,
  ``co_probe2_rr_raw, ``co_probe2_sr_raw,
  ``co_tick_probe2_rr_raw, ``co_tick_probe2_sr_raw,
  ``co_schedC_sr, ``co_tick_schedC_sr,
  ``co_lowerC_rr, ``co_lowerC_sr, ``co_tick_lowerC_rr, ``co_tick_lowerC_sr,
  ``co_map_rr, ``co_map_sr, ``co_filterMap_rr, ``co_filterMap_sr,
  ``co_broadcast_rr, ``co_broadcast_sr, ``co_demux_rr, ``co_demux_sr,
  ``co_values_rr, ``co_values_sr,
  ``co_weaken_retries_rr, ``co_weaken_retries_sr,
  ``co_union_rr, ``co_union_sr,
  ``co_assume_ordering_rr, ``co_assume_ordering_sr,
  ``co_fold_rr, ``co_fold_sr, ``co_fold_monotone_rr, ``co_fold_monotone_sr,
  ``co_snapshot_rr, ``co_snapshot_sr, ``co_batch_rr, ``co_batch_sr,
  ``co_batch_ordered_rr, ``co_batch_ordered_sr,
  ``co_mapBatchWith_rr, ``co_mapBatchWith_sr,
  ``co_mapBatch_rr, ``co_mapBatch_sr,
  ``co_mapBatchesWith_rr, ``co_mapBatchesWith_sr,
  ``co_filterMapBatchesWith_rr, ``co_filterMapBatchesWith_sr,
  ``co_scan_batches_across_ticks_rr, ``co_scan_batches_across_ticks_sr,
  ``co_fold_batches_across_ticks_monotone_rr,
  ``co_fold_batches_across_ticks_monotone_sr,
  ``co_scan_batches_unordered_across_ticks_rr,
  ``co_scan_batches_unordered_across_ticks_sr,
  ``co_scan_batches_unordered_rr, ``co_scan_batches_unordered_sr,
  ``co_scan_batches_unordered₂_rr, ``co_scan_batches_unordered₂_sr,
  ``co_scan_across_ticks_rr, ``co_scan_across_ticks_sr,
  ``co_mapTick_rr, ``co_mapTick_sr, ``co_zipTick_rr, ``co_zipTick_sr,
  ``co_fold_across_ticks_monotone_rr,
  ``co_fold_across_ticks_monotone_sr,
  ``co_mapMonotone_rr, ``co_mapMonotone_sr,
  ``co_forgetBound_rr, ``co_forgetBound_sr, ``co_defer_rr, ``co_defer_sr,
  ``co_sample_every_rr, ``co_sample_every_sr,
  ``co_timeout_snapshot_rr, ``co_timeout_snapshot_sr,
  ``co_source_interval_batch_rr, ``co_source_interval_batch_sr,
  ``co_mapBatchesUnordered_rr, ``co_mapBatchesUnordered_sr,
  ``co_emitBatches_rr, ``co_emitBatches_sr,
  ``co_emitMultisetBatches_rr, ``co_emitMultisetBatches_sr,
  ``co_emitBatchesUnordered_rr, ``co_emitBatchesUnordered_sr,
  ``co_allTicks_rr, ``co_allTicks_sr,
  ``co_hfix_stream_rr, ``co_hfix_stream_sr,
  ``co_hfix_tick_rr, ``co_hfix_tick_sr,
  ``values_hfix_stream', ``values_hfix_tick',
  ``sched_hfix_stream', ``sched_hfix_tick',
  ``values_broadcast_unit, ``values_demux_unit,
  ``values_emitMultisetBatches_unit,
  ``sched_assume_ordering_unit, ``sched_snapshot_unit,
  ``sched_batch_unit,
  ``sched_batch_ordered_unit, ``sched_assume_ordering_batch_unit,
  ``sched_fix_stream_unit, ``sched_fix_tick_unit]

/-- Simp an expression as a TERM, returning `(e', proof e = e')`
(`proof = none` when unchanged). -/
def simpTerm (e : Expr) (lemmas : Array Name) :
    TermElabM (Expr × Option Expr) := do
  let mut st : SimpTheorems := {}
  for n in lemmas do
    if let some ci := (← getEnv).find? n then
      -- Theorems are simp rules; defs (e.g. wrappers like `leCore`)
      -- must go in as unfold targets instead.
      if ci.isTheorem then
        st ← st.addConst n
      else
        st ← st.addDeclToUnfold n
  let ctx ← Simp.mkContext (simpTheorems := #[st])
  let (res, _) ← simp e ctx
  pure (res.expr, res.proof?)

/-- The module's corner body at the leg (delta+beta, lets zeta'd by
the simp pass), as an open term over the module binders. -/
def glueBodyAt (mc : ModCtx) (interp : Expr) (mapped : Array Expr)
    (leg : List LegStep) : TermElabM Expr := do
  let info ← getConstInfo mc.mName
  let some v := info.value? |
    throwError "HydroGen: {mc.mName} has no value"
  let app := (v.beta (mc.ctxArgs ++ #[interp] ++
    mapped[0:mc.realCount])).headBeta
  let app ← applyLeg app mc.legPre
  let app := mkAppN app mapped[mc.realCount:mapped.size]
  applyLeg app leg

/-- Collect `(decRecordType, term)` for registered callee applications
at the `Values` interpretation inside `t`. -/
partial def collectValuesDecArgs (mc : ModCtx) (t : Expr) :
    TermElabM (Array (Expr × Expr)) := do
  go t #[]
where
  go (e : Expr) (acc0 : Array (Expr × Expr)) :
      TermElabM (Array (Expr × Expr)) := do
    let env ← getEnv
    match e with
    | .app .. =>
      let f := e.getAppFn
      let mut acc := acc0
      if let .const c _ := f then
        if (getGenInfo env c).isSome then
          for a in e.getAppArgs do
            let ty ← inferType a
            if let .const tn _ := ty.getAppFn then
              if isStructure env tn &&
                  ty.getAppArgs.any (· == mc.values) then
                acc := acc.push (ty, a)
      for a in e.getAppArgs do
        acc ← go a acc
      go f acc
    | .lam _ _ b _ | .forallE _ _ b _ => go b acc0
    | .letE _ _ v b _ => go b (← go v acc0)
    | .mdata _ b | .proj _ _ b => go b acc0
    | _ => pure acc0

/-- The glue module's `Values`-side decision record, extracted from
the discovered term: whole-record passthrough when a callee consumes
the module's record type directly; otherwise field-wise (sub-records
by type match against callee decision args, `fixd` at `Td + 1`,
machine/values-pass prims from the corner record). -/
def extractGlueVdec (mc : ModCtx) (ts : Array Expr) : TermElabM Expr := do
  let recIdx ← do
    let mut r := none
    for i in [0:mc.args.size] do
      if let .decRec _ := mc.kinds[i]! then r := some i
    match r with
    | some i => pure i
    | none => throwError "HydroGen: {mc.mName}: glue module has no \
        decision record"
  let recTyV := reinterp mc.corner mc.values
    (← inferType mc.args[recIdx]!)
  let mut found := #[]
  for t in ts do
    found := found ++ (← collectValuesDecArgs mc t)
  if found.isEmpty then
    throwError "HydroGen: {mc.mName}: discovery found no Values-side \
      callee decision args; discovered terms:\n{ts}"
  -- whole-record passthrough
  for (ty, a) in found do
    if ← isDefEq ty recTyV then
      return a
  -- field-wise
  let .const s _ := recTyV.getAppFn |
    throwError "HydroGen: glue record head"
  let ctor := getStructureCtor (← getEnv) s
  let mut fields := #[]
  for f in getStructureFields (← getEnv) s do
    let pC ← mkProjection mc.args[recIdx]! f
    let ptyC ← whnfR (← inferType pC)
    let ptyV := reinterp mc.corner mc.values ptyC
    let v ← do
      if let .const n _ := ptyC.getAppFn then
        if let some df := decFamOfHead n then
          match df with
          | .fixd => mkAppM ``HAdd.hAdd #[mc.Td, mkNatLit 1]
          | _ =>
            if df.valuesPass then pure pC
            else pure (mkConst ``Unit.unit)
        else
          -- a sub-record: find it among the callee decision args
          let mut r := none
          for (ty, a) in found do
            if r.isNone then
              if ← isDefEq ty ptyV then r := some a
          match r with
          | some a => pure a
          | none => throwError "HydroGen: {mc.mName}: no callee \
              consumes record field {f} ({ptyV})"
      else throwError "HydroGen: glue field {f}"
    fields := fields.push v
  mkAppOptM ctor.name
    ((recTyV.getAppArgs ++ fields).map some)

/-- The corner-side chain for a glue leg: `lhs ≡ bodyC` (one module
delta), simp (callee namings fold most redexes), then the residual
pass (dependent-position redexes simp cannot reach). Returns the
proof `lhs = tC` together with `tC`. -/
def glueCornerChain (lhs bodyC : Expr) (simpC : Array Name)
    (resLems : Array (Name × LemKey)) (cache : MatchCache) :
    TermElabM (Expr × Expr) := do
  let bodyC ← zetaAll bodyC
  let (tC0, prfC?) ← simpTerm bodyC simpC
  let step ← mkExpectedTypeHint (← mkEqRefl bodyC) (← mkEq lhs bodyC)
  let step ← match prfC? with
    | some p => mkEqTrans step p
    | none => pure step
  let mut st ← RwSt.ofProof step lhs tC0
  -- alternate residual rewriting with simp re-normalization: terms a
  -- residual rewrite introduces (callee-lemma RHS instantiations)
  -- must reach the same simp-normal form as the module side (e.g.
  -- contract matches inside subtype type args)
  for _ in [0:4] do
    let rhs0 := st.rhs
    st ← st.rwResiduals resLems cache
    let (t', prf?) ← simpTerm st.rhs simpC
    if let some p := prf? then
      st := { st with rhs := t',
                      prf := ← mkEqTrans st.prf p }
    if st.rhs == rhs0 then break
  pure (st.prf, st.rhs)

/-- The two-sided glue leg proof for `lhs = rhs`: corner chain (delta
+ simp + residuals) meets the module side (delta + wrapper/vdec
unfolds — no corner apps exist on that side) SYNTACTICALLY. Any gap
is a generator bug (the two spellings must coincide by construction)
and is reported with both spellings. The kernel then only ever checks
one-delta `rfl`s and congruence steps — never a module-scale defeq
through the knots' opaque choice fuels (which is not definitional and
previously surfaced as kernel timeouts/mismatches). -/
def glueLegProof (mc : ModCtx) (lhs bodyC : Expr) (simpC : Array Name)
    (resLems : Array (Name × LemKey)) (rhs bodyR : Expr)
    (simpR : Array Name) (cache : MatchCache) :
    TermElabM Expr := do
  let (stepC, tC) ← glueCornerChain lhs bodyC simpC resLems cache
  -- the module side runs the SAME chain (corner-shaped lemmas cannot
  -- match it; the shared normalizers keep the two sides confluent)
  let (stepR, tR) ← glueCornerChain rhs bodyR simpR resLems cache
  unless tC == tR do
    -- structural miss: tolerate residual TYPE-argument differences
    -- (matcher apps inside subtype predicates that simp cannot
    -- reach) via reducible defeq — cheap when the trees otherwise
    -- share structure; anything else is a generator bug
    unless ← withReducible <| isDefEq tC tR do
      let _ ← meetError mc.mName "glue leg" tC tR
  mkExpectedTypeHint (← mkEqTrans stepC (← mkEqSymm stepR))
    (← mkEq lhs rhs)

/-- Generate the glue module's naming stack: per-leg `M_co_srᵢ` and
`M_co_rrᵢ` (at the named `M_vdec`), by simp discovery. -/
def genGlue (mc : ModCtx) : TermElabM (Array Name × Array Name × Name) := do
  let rules ← calleeNamingRules mc.mName
  let collapse : Array Name :=
    #[``co_probeC_sr, ``co_probeC_rr, ``co_schedC_sr,
      ``co_probe2_sr, ``co_probe2_rr, ``co_schedEmbed_sr,
      ``co_tick_probeC_sr, ``co_tick_probeC_rr, ``co_tick_schedC_sr,
      ``co_tick_probe2_sr, ``co_tick_probe2_rr,
      ``co_tick_schedEmbed_sr, ``co_input_sr, ``co_input_rr,
      ``co_tick_input_sr, ``co_tick_input_rr]
  let simpSet := rules ++ collapse ++ mc.extras
  -- residual pass: redexes in dependent argument positions (blocked
  -- for simp's congruence) and combinator trees wrapping callee legs
  -- — the full per-op set, applied one targeted rewrite at a time
  let resLems ← (coSimpBase ++ collapse ++ rules).mapM fun l => do
    pure (l, ← lemKeyOf l)
  let cache : MatchCache ← IO.mkRef {}
  -- ===== machine legs =====
  let srArgs ← mc.srArgs
  let mut srNames := #[]
  for i in [0:mc.legs.size] do
    let leg := mc.legs[i]!
    let lhs ← mkProjection (← mc.legAppAt mc.corner mc.args leg) `sr
    let bodyC ← mkProjection
      (← glueBodyAt mc mc.corner mc.args leg) `sr
    let rhs ← mc.legAppAt mc.sched srArgs leg
    let bodyR ← glueBodyAt mc mc.sched srArgs leg
    let prf ← glueLegProof mc lhs bodyC simpSet resLems rhs bodyR
      simpSet cache
    let name := mc.mName.appendAfter s!"_co_sr{subscript (i + 1)}"
    let stmt ← mkForallFVars mc.allBinders (← mkEq lhs rhs)
    addThm name stmt (← mkLambdaFVars mc.allBinders prf)
    srNames := srNames.push name
  -- ===== denotational legs =====
  -- discover on EVERY leg (record slices may be consumed leg-wise:
  -- `pcBody`'s `sp` slice only appears in the payload legs), extract
  -- the record, then name it in the genRrEx binder convention
  -- (outers abstracted)
  let mut cornerChains : Array (Expr × Expr × Expr) := #[]
  for i in [0:mc.legs.size] do
    let leg := mc.legs[i]!
    let lhs ← mkProjection (← mc.legAppAt mc.corner mc.args leg) `rr
    let bodyC ← mkProjection
      (← glueBodyAt mc mc.corner mc.args leg) `rr
    let (stepC, tC) ← glueCornerChain lhs bodyC simpSet resLems cache
    cornerChains := cornerChains.push (lhs, stepC, tC)
  let vdecRec ← extractGlueVdec mc (cornerChains.map (·.2.2))
  -- abstract over the machine outers (genRrEx order)
  let mut outerVals : Array Expr := #[]
  let mut outerTys : Array (Name × Expr) := #[]
  for i in [0:mc.args.size] do
    match mc.kinds[i]! with
    | .wire _ =>
      outerVals := outerVals.push (← mkProjection mc.args[i]! `sr)
      outerTys := outerTys.push (Name.mkSimple s!"x{i}",
        reinterp mc.corner mc.sched (← inferType mc.args[i]!))
    | .primDec f =>
      if f.schedPass && !f.isContent then
        outerVals := outerVals.push mc.args[i]!
        outerTys := outerTys.push (Name.mkSimple s!"d{i}",
          reinterp mc.corner mc.sched (← inferType mc.args[i]!))
    | .decRec _ =>
      for (path, f) in flattenTree (mc.trees[i]!).get! do
        if f.schedPass && !f.isContent then
          let pv ← applyFieldPath mc.args[i]! path
          outerVals := outerVals.push pv
          outerTys := outerTys.push
            (Name.mkSimple (s!"d{i}_" ++
              String.intercalate "_" (path.map toString)),
             reinterp mc.corner mc.sched (← inferType pv))
    | .plain => pure ()
  let plainArgs := (mc.args.zip mc.kinds).filterMap fun (a, k) =>
    if k == .plain then some a else none
  let vdecName := mc.mName.appendAfter "_vdec"
  let vdecVal ← withLocalDecls
      (outerTys.map fun (n, ty) =>
        (n, BinderInfo.default, fun _ => pure ty)) fun outs => do
      let mut absd := vdecRec
      for v in outerVals, o in outs do
        absd := (← kabstract absd v).instantiate1 o
      let exBinders := mc.ctxArgs ++ #[mc.pacing, mc.Td] ++ plainArgs
        ++ outs
      if absd.hasFVar then
        for a in mc.args, k in mc.kinds do
          if k != .plain && absd.containsFVar a.fvarId! then
            throwError "HydroGen: {mc.mName}: vdec extraction left a \
              corner binder ({a}) unabstracted"
      mkLambdaFVars exBinders absd
  addDefn vdecName (← inferType vdecVal) vdecVal
  -- the vdec applied back at the module's own outers
  let exBindersVals := mc.ctxArgs ++ #[mc.pacing, mc.Td] ++ plainArgs
    ++ outerVals
  let vdecApp := mkAppN (mkConst vdecName) exBindersVals
  -- rr args: wires .rr, the record at the named vdec
  let mut rrArgs := #[]
  for a in mc.args, k in mc.kinds do
    match k with
    | .wire _ => rrArgs := rrArgs.push (← mkProjection a `rr)
    | .decRec _ => rrArgs := rrArgs.push vdecApp
    | .primDec .fixd =>
      rrArgs := rrArgs.push (← mkAppM ``HAdd.hAdd #[mc.Td, mkNatLit 1])
    | .primDec f =>
      if f.valuesPass then rrArgs := rrArgs.push a
      else rrArgs := rrArgs.push (mkConst ``Unit.unit)
    | .plain => rrArgs := rrArgs.push a
  let mut rrNames := #[]
  for i in [0:mc.legs.size] do
    let leg := mc.legs[i]!
    let (lhs, stepC, tC) := cornerChains[i]!
    let rhs ← mc.legAppAt mc.values rrArgs leg
    let bodyR ← glueBodyAt mc mc.values rrArgs leg
    -- the module side spells the vdec folded; unfold it so both sides
    -- meet at the discovered record spelling
    let (stepR, tR) ← glueCornerChain rhs (← zetaAll bodyR)
      (simpSet.push vdecName) resLems cache
    unless tC == tR do
      unless ← withReducible <| isDefEq tC tR do
        let _ ← meetError mc.mName s!"glue rr leg {i}" tC tR
    let prf ← mkExpectedTypeHint
      (← mkEqTrans stepC (← mkEqSymm stepR)) (← mkEq lhs rhs)
    let name := mc.mName.appendAfter s!"_co_rr{subscript (i + 1)}"
    let stmt ← mkForallFVars mc.allBinders (← mkEq lhs rhs)
    addThm name stmt (← mkLambdaFVars mc.allBinders prf)
    rrNames := rrNames.push name
  pure (srNames, rrNames, vdecName)

/-! ## Glue monotonicity (compositional: callee mono lemmas resolved
recursively — module-scale `MonoRel` projection is not definitional
through a callee's knots, and unfolding callees was the cost center) -/

/-- An arbitrary inhabitant of `ty` (Π-types get constant functions):
statement binders the conclusion+hypotheses do not pin can take any
value. -/
partial def arbValue (ty : Expr) : TermElabM (Option Expr) := do
  let ty ← instantiateMVars ty
  if ty.isForall then
    forallTelescope ty fun bs cod => do
      match ← arbValue cod with
      | some v => pure (some (← mkLambdaFVars bs v))
      | none => pure none
  else if ty.isConstOf ``Nat then
    pure (some (mkNatLit 0))
  else if ty.isAppOf ``Nat.le then
    observing? (mkAppOptM ``Nat.le.refl
      #[some (← instantiateMVars (ty.getArg! 0))])
  else
    match ← observing? (synthInstance ty) with
    | some v => pure (some v)
    | none =>
      match ← observing?
          (mkAppOptM ``Inhabited.default #[ty, none]) with
      | some v => pure (some v)
      | none =>
        if let .const tc _ := ty.getAppFn then
          match (← getEnv).find? tc with
          | some (.inductInfo ii) =>
            match ii.ctors.head? with
            | some c0 =>
              observing? do
                -- FULLY applied (fields defaulted recursively): a
                -- partial constructor application type-checks as a
                -- function and slips past `assign`
                let mut r ← mkAppOptM c0 (ty.getAppArgs.map some)
                for _ in [0:32] do
                  let rTy ← whnfR (← inferType r)
                  unless rTy.isForall do break
                  let some v ← arbValue rTy.bindingDomain!
                    | throwError "no field default"
                  r := mkApp r v
                unless ← isDefEq (← inferType r) ty do
                  throwError "ctor default type mismatch"
                pure r
            | none => pure none
          | _ => pure none
        else pure none

/-- Resolve a graded-relation goal `T` from the statement hypotheses
or by instantiating a callee's mono lemma (conclusion unified with
`T` at default transparency — the module delta this crosses is
zeta/beta/proj only, every callee stays FOLDED — hypothesis
metavariables resolved recursively). -/
partial def resolveRel (hyps : Array Expr)
    (monoOf : Name → Array Name) (calleeNames : Array Name)
    (T : Expr) (depth : Nat) : TermElabM (Option Expr) := do
  for h in hyps do
    if ← withReducible <| isDefEq (← inferType h) T then
      return some h
  if depth == 0 then return none
  -- callee mono lemmas whose module occurs in T (or in what T deltas
  -- to — the folded M-app conclusion mentions only M, so fall back to
  -- trying every callee)
  let mentioned := calleeNames.filter fun c =>
    (T.find? (·.isConstOf c)).isSome
  let order := if mentioned.isEmpty then calleeNames else mentioned
  -- unify under T's binder telescope: the lemma's own trailing
  -- binders (`∀ i`) are part of its meta-telescope and get assigned
  -- to the locals during unification
  forallTelescope T fun is T' => do
  for K in order do
    for lem in monoOf K do
      let diag := (← IO.getEnv "HYDROGEN_MONO_DIAG").isSome
      let res ← observing? do
        let lemC ← mkConstWithFreshMVarLevels lem
        let (ms, _, ty) ← forallMetaTelescope (← inferType lemC)
        unless ← isDefEq ty T' do
          if diag then
            let (tyS, tS) ← withOptions
                (fun o => o.setBool `pp.explicit true) do
              pure (← ppExpr (← instantiateMVars ty), ← ppExpr T')
            IO.eprintln s!"[mono-diag d{depth}] {lem} concl:\n\
              {tyS}\n≠\n{tS}"
          throwError "no match"
        if diag then
          IO.eprintln s!"[mono-diag d{depth}] {lem} concl matched"
        -- pass 1: Prop (hypothesis) mvars — resolving them against
        -- the available hypotheses also PINS wire mvars the
        -- conclusion left loose
        for m in ms do
          unless ← m.mvarId!.isAssigned do
            let mty ← instantiateMVars (← m.mvarId!.getType)
            if (← inferType mty).isProp then
              let some prf ← resolveRel hyps monoOf calleeNames mty
                  (depth - 1)
                | do
                  if diag then
                    IO.eprintln s!"[mono-diag d{depth}] {lem} hyp \
                      unresolved:\n{← ppExpr mty}"
                  throwError "unresolved hypothesis"
              m.mvarId!.assign prf
        -- pass 2: leftovers the statement does not pin (fuel
        -- horizons, enum parameters the leg's value ignores,
        -- instances): any value proves the instantiation
        for m in ms do
          unless ← m.mvarId!.isAssigned do
            let mty ← instantiateMVars (← m.mvarId!.getType)
            match ← arbValue mty with
            | some v => m.mvarId!.assign v
            | none =>
              if diag then
                IO.eprintln s!"[mono-diag d{depth}] {lem} \
                  unpinned mvar: {← ppExpr mty}"
              throwError "unpinned metavariable"
        -- strays: unification can mint mvars outside `ms` (instances,
        -- delayed-abstracted enum parameters)
        let ans ← instantiateMVars (mkAppN lemC ms)
        for m in (← getMVars ans) do
          let mty ← instantiateMVars (← m.getType)
          match ← arbValue mty with
          | some v => m.assign v
          | none =>
            if diag then
              IO.eprintln s!"[mono-diag d{depth}] {lem} stray \
                mvar: {← ppExpr mty}"
            throwError "stray metavariable"
        mkLambdaFVars is (← instantiateMVars ans)
      if let some prf := res then return some prf
  return none

/-- Per-leg `Values` monotonicity for a glue module, by composition of
the callees' mono lemmas (statement scaffolding as in `genMono`).
Legs that are not resolvable compositions (combinator-wrapped
outputs no consumer needs) are skipped: the registered array stays
leg-ALIGNED with `Name.anonymous` placeholders. -/
def genGlueMono (mc : ModCtx) : TermElabM (Array Name) := do
  let env ← getEnv
  let callees ← calleeInfos mc.mName
  let calleeNames := callees.map (·.1)
  let monoOf : Name → Array Name := fun n =>
    match getGenInfo env n with
    | some gi => gi.monoLemmas.filter (· != Name.anonymous)
    | none => #[]
  -- ==== binder scaffolding (mirrors genMono) ====
  let mut decls : Array (Name × BinderInfo × Expr) := #[]
  for i in [0:mc.args.size] do
    let ty := reinterp mc.corner mc.values (← inferType mc.args[i]!)
    let nm ← mc.args[i]!.fvarId!.getUserName
    match mc.kinds[i]! with
    | .wire _ =>
      decls := decls.push (nm, .implicit, ty)
      decls := decls.push (nm.appendAfter "'", .implicit, ty)
    | .plain => pure ()
    | _ => decls := decls.push (nm, .default, ty)
  withLocalDecls (decls.map fun (n, bi, ty) =>
      (n, bi, fun _ => pure ty)) fun xs => do
  let mut fstOf : Std.HashMap Nat Expr := {}
  let mut sndOf : Std.HashMap Nat Expr := {}
  let mut j := 0
  for i in [0:mc.args.size] do
    match mc.kinds[i]! with
    | .wire _ =>
      fstOf := fstOf.insert i xs[j]!
      sndOf := sndOf.insert i xs[j+1]!
      j := j + 2
    | .plain =>
      fstOf := fstOf.insert i mc.args[i]!
      sndOf := sndOf.insert i mc.args[i]!
    | _ =>
      fstOf := fstOf.insert i xs[j]!
      sndOf := sndOf.insert i xs[j]!
      j := j + 1
  let mut argBinders : Array Expr := #[]
  for i in [0:mc.args.size] do
    match mc.kinds[i]! with
    | .wire _ =>
      argBinders := argBinders.push (fstOf.get? i).get!
      argBinders := argBinders.push (sndOf.get? i).get!
    | .plain => argBinders := argBinders.push mc.args[i]!
    | _ => argBinders := argBinders.push (fstOf.get? i).get!
  let mut hypDecls : Array (Name × BinderInfo × Expr) := #[]
  for i in [0:mc.args.size] do
    if let .wire cf := mc.kinds[i]! then
      let ty := reinterp mc.corner mc.values (← inferType mc.args[i]!)
      let rel ← valuesRelOf cf ty (fstOf.get? i).get! (sndOf.get? i).get!
      hypDecls := hypDecls.push
        (Name.mkSimple s!"hm{i}", .default, rel)
  withLocalDecls (hypDecls.map fun (n, bi, ty) =>
      (n, bi, fun _ => pure ty)) fun hyps => do
  let fstAll := (Array.range mc.args.size).map fun i => (fstOf.get? i).get!
  let sndAll := (Array.range mc.args.size).map fun i => (sndOf.get? i).get!
  -- ==== per-leg lemmas ====
  let mut names := #[]
  for i in [0:mc.legs.size] do
    let leg := mc.legs[i]!
    let legHead := mc.legTys[i]!.getAppFn
    let cf ← match legHead with
      | .const n _ =>
        match carrierFamOfHead n with
        | some cf => pure cf
        | none => throwError "HydroGen: {mc.mName}: mono leg {i}"
      | _ => throwError "HydroGen: {mc.mName}: mono leg {i} head"
    let legTyV := reinterp mc.corner mc.values mc.legTys[i]!
    let concl ← valuesRelOf cf legTyV
      (← mc.legAppAt mc.values fstAll leg)
      (← mc.legAppAt mc.values sndAll leg)
    -- resolve against NORMALIZED subjects (module delta + zeta +
    -- tuple projections): the callee applications appear with
    -- concrete arguments, so conclusion unification pins every
    -- lemma binder structurally (a folded subject lets the unifier
    -- match through reduction while leaving binders loose). The
    -- folded statement is recovered by a fix-free defeq hint.
    let normLeg := fun (args : Array Expr) => do
      let b ← zetaAll (← glueBodyAt mc mc.values args leg)
      pure (← simpTerm b (mc.extras ++
        (← calleeInfos mc.mName).foldl (init := #[])
          fun acc (c, gi) => acc ++ gi.inlines)).1
    let conclN ← valuesRelOf cf legTyV
      (← normLeg fstAll) (← normLeg sndAll)
    match ← resolveRel hyps monoOf calleeNames conclN 6 with
    | some prfN =>
      let prf ← mkExpectedTypeHint prfN concl
      let stmt ← mkForallFVars
        (mc.ctxArgs ++ argBinders ++ hyps) concl
      let name := mc.mName.appendAfter s!"_mono{subscript (i + 1)}"
      let val ← instantiateMVars
        (← mkLambdaFVars (mc.ctxArgs ++ argBinders ++ hyps) prf)
      if val.hasExprMVar || val.hasLevelMVar then
        let mvars ← getMVars val
        let tys ← mvars.mapM fun m => do
          pure (toString (← ppExpr (← instantiateMVars (← m.getType))))
        IO.eprintln s!"[mono-diag] {name} residual mvars: \
          {tys} (lvl: {val.hasLevelMVar})"
        names := names.push Name.anonymous
      else
        addThm name stmt val
        names := names.push name
    | none =>
      -- placeholder keeps the array leg-aligned
      names := names.push Name.anonymous
  pure names

initialize
  glueMonoHook.set (some genGlueMono)

elab "hydro_glue " M:ident ids:(hydroGenIds)? : command => do
  let mName ← liftCoreM <| realizeGlobalConstNoOverload M
  let extras ← elabExtras (ids.map (·.raw))
  let extras := extrasWithSpec (← getEnv) mName extras
  let (srs, rrs, vdec) ← liftTermElabM <|
    withModCtx mName (extras := extras) fun mc => genGlue mc
  registerInfo mName fun gi =>
    { gi with srLemmas := srs, rrLemmas := rrs, vdec? := some vdec,
              pinLemmas := #[] }
  logInfo m!"hydro_glue {mName}: {srs.size} sr, {rrs.size} rr (+vdec)"

end HydroGen

end HydroV2
