[package]
name = "wasm_test_site"
version = "0.1.0"
authors = ["Mingwei Samuel <mingwei.samuel@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gloo = {  version = "0.11.0", features = ["futures"] }
hydroflow = { path = "../hydroflow" }
pharos = "0.5"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.43"
web-sys = { version = "0.3.51", features = [ "console", "Window", "Document", "Element", "HtmlElement", "HtmlInputElement", "EventTarget"] }
ws_stream_wasm = "0.7.0"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = "0.1.7"
futures = "0.3.30"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
