[package]
name = "hydroflow_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
hydroflow_internalmacro = { path = "../hydroflow_internalmacro" }
proc-macro2 = "1.0.0"
quote = "1.0.0"
serde = "1.0.1"
serde_json = "1.0.8"
slotmap = { version = "1.0.6", features = ["serde"] }
syn = { version = "1.0.0", features = [ "parsing", "extra-traits" ] }
