[package]
name = "hydroflow_lang"
version = "0.1.0"
edition = "2021"

[features]
default = []
diagnostics = []

[dependencies]
hydroflow_internalmacro = { path = "../hydroflow_internalmacro" }
once_cell = "1.17"
proc-macro2 = { version = "1.0.0", features = ["span-locations"] }
quote = "1.0.0"
regex = "1.7.0"
serde = "1.0.1"
serde_json = "1.0.8"
slotmap = { version = "1.0.6", features = ["serde"] }
syn = { version = "1.0.0", features = [ "extra-traits", "full", "parsing" ] }

[dev-dependencies]
prettyplease = "0.1.22"
