[package]
name = "hydro_deploy"
publish = true
version = "0.8.0"
edition = "2021"
license = "Apache-2.0"
documentation = "https://docs.rs/hydro_deploy/"
description = "Hydro Deploy"

[dependencies]
anyhow = { version = "1", features = [ "backtrace" ] }
async-process = "2.2"
async-recursion = "1"
async-ssh2-lite = { version = "0.5.0", features = [ "tokio" ] }
async-trait = "0.1"
buildstructor = "0.5"
bytes = "1.1.0"
cargo_metadata = "0.18"
dunce = "1"
dyn-clone = "1"
futures = "0.3"
futures-core = "0.3"
hydroflow_deploy_integration = { path = "../hydroflow_deploy_integration", version = "^0.5.2" }
indicatif = "0.17"
inferno = "0.11"
memo-map = "0.3"
nanoid = "0.4"
nix = { version = "0.29", features = [ "signal" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
shell-escape = "0.1"
tempfile = "3"
tokio = { version = "1", features = [ "full" ] }
tokio-stream = { version = "0.1", default-features = false }
tokio-util = { version = "0.7", features = [ "io-util" ] }
