[package]
name = "hydroflow"
version = "0.1.0"
edition = "2021"

[features]
default = [ "async", "macros" ]
async = [ "futures" ]
macros = [ "hydroflow_macro", "hydroflow_datalog" ]

[[example]]
name = "book"

[[example]]
name = "chat"

[[example]]
name = "covid_tracing"

[[example]]
name = "covid_tracing_dist"

[[example]]
name = "graph_reachability"

[[example]]
name = "three_clique"

[[example]]
name = "two_pc"

[[example]]
name = "kvs"

[dependencies]
bincode = "1.3"
byteorder = "1.4.3"
bytes = "1.1.0"
futures = { version = "0.3", optional = true }
hydroflow_lang = { path = "../hydroflow_lang" }
hydroflow_macro = { optional = true, path = "../hydroflow_macro" }
hydroflow_datalog = { optional = true, path = "../hydroflow_datalog" }
ref-cast = "1.0"
sealed = "0.4"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
slotmap = "1.0"
static_assertions = "1.1.0"
tokio = { version = "1.16", features = [ "full" ] }
tokio-util = { version = "0.6.9", features = [ "codec" ] }
tuple_list = "0.1"

[dev-dependencies]
chrono = { version = "0.4", features = [ "serde" ] }
clap = { version = "3.0.14", features = [ "derive" ] }
colored = "2.0"
criterion = { version = "0.3", features = [ "async_tokio" ] }
futures = { version = "0.3" }
itertools = "0.10.3"
rand = "0.8.4"
time = "0.3"
tokio-stream = { version = "0.1.8", features = [ "io-util" ] }
hdrhistogram = "7"
zipf = "7.0.0"
core_affinity = "0.5.10"