[package]
name = "hydroflow"
version = "0.1.0"
edition = "2021"

[features]
default = [ "async", "variadic_generics" ]
async = [ "futures" ]
variadic_generics = []

[dependencies]
bytes = "1.1.0"
futures = { version = "0.3", optional = true }
ref-cast = "1.0"
sealed = "0.3"
slotmap = "1.0"
static_assertions = "1.1.0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["codec"] }
tuple_list = "0.1"

[dev-dependencies]
criterion = { version = "0.3", features = [ "async_tokio" ] }
