[package]
name = "flow_macro"
publish = false
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true
path = "../flow/src/lib.rs"

[features]
default = ["macro"]
macro = []

[dependencies]
# make sure to sync these to `flow`!
hydroflow_plus = { git = "{{ hydroflow_git | default: 'https://github.com/hydro-project/hydroflow.git' }}", branch = "{{ hydroflow_branch | default: 'main' }}" }
hydroflow_plus_cli_integration = { git = "{{ hydroflow_git | default: 'https://github.com/hydro-project/hydroflow.git' }}", branch = "{{ hydroflow_branch | default: 'main' }}" }
stageleft = { git = "{{ hydroflow_git | default: 'https://github.com/hydro-project/hydroflow.git' }}", branch = "{{ hydroflow_branch | default: 'main' }}" }
tokio = { version = "1.16", features = ["full"] }

[build-dependencies]
stageleft_tool = { git = "{{ hydroflow_git | default: 'https://github.com/hydro-project/hydroflow.git' }}", branch = "{{ hydroflow_branch | default: 'main' }}" }
