import HydroLean.Hydro.Growth

/-!
# Causal availability — the shelved design for gateless loops

**Status: shelved framework (keep) — adopt when a program with a gateless
self-influencing loop arrives.** See docs/11-causal-availability.md and
FINDINGS D21 for the boundary rule: loops whose triggers route through
`forward_ref` cycle wires inherit tick causality from the fixpoint (Paxos —
`leader_ballot_stable` is derived without this file); gateless loops do
not, and this is the compiled mechanism for them.

Design question (docs/11-causal-availability.md): when a
location's tick loop consumes data whose production *depends on the
location's own outputs*, the current combinators check batch/snapshot
legality against the COMPLETED availability — admitting acausal cuts
(consume a reply before the request that caused it is sent). Paxos's
election happens to exclude the resulting violations by protocol structure
(`AcausalExploration.lean`: the trigger gate starves fabricated reigns),
but a gateless program has no such protection (`Programs/CausalToy.lean`
exhibits a realizable violation under plain `batchC`).

Two formalizations, in one file because one is the other's face:

- **Option C (definitional)**: `causalTickLoop` — the atomic-tick-region
  combinator. Tick `t` draws its consumed batch from
  `env(own outputs through tick t-1)` (inputs-before-outputs within the
  tick; `env : →ₘ`, so availability families are monotone by type). Same
  blocking style as `batchC`; **`batchC` is exactly the
  constant-environment special case** (`causalTickLoop_const`). This is
  the tick-indexed guarded fixpoint: consumed/produced are mutually
  recursive over ticks, guarded by the strict output prefix.

- **Option A (the knowledge face)**: `CausalCuts` — the per-tick
  containment predicate proofs consume. NOT a hypothesis when Option C is
  the definition: `causalTickLoop_causal` DERIVES it for every realized
  run (Option A is Option C's elimination principle). For a program still
  written with plain `batchC`, `CausalCuts` can instead be assumed as
  decision-bundle wellformedness — the migration path.

No existing definition changes; nothing else imports this file yet.
-/

namespace HydroLean.Hydro

universe u v w

variable {α : Type u} {β : Type v} {σ : Type w}

/-! ## Availability families -/

/-- What the environment can have produced in response to my first `t`
output ticks: the (monotone) environment pipeline applied to the strict
output prefix. `env` is the composite other side of the loop (e.g. the
acceptor pipeline); for a source that does not depend on me, `env` is
constant and the family degenerates to the completed availability. -/
def availAt (env : List β →ₘ List α) (outs : List (List β)) (t : Nat) :
    List α :=
  env.f (outs.take t).flatten

/-- Availability families are monotone in the tick index — by the `→ₘ`
type of the environment, never a per-program proof. -/
theorem availAt_mono (env : List β →ₘ List α) (outs : List (List β))
    {t t' : Nat} (h : t ≤ t') :
    availAt env outs t <+: availAt env outs t' := by
  refine env.mono (prefix_flatten ?_)
  rw [show outs.take t = (outs.take t').take t from by
    rw [List.take_take, Nat.min_eq_left h]]
  exact List.take_prefix t _

/-- Availability families are monotone under output growth (more realized
ticks never shrink what was available). -/
theorem availAt_mono_outs (env : List β →ₘ List α)
    {outs outs' : List (List β)} (h : outs <+: outs') (t : Nat) :
    availAt env outs t <+: availAt env outs' t := by
  refine env.mono (prefix_flatten ?_)
  obtain ⟨u, rfl⟩ := h
  rcases Nat.le_total t outs.length with hle | hle
  · rw [List.take_append_of_le_length hle]
    exact List.prefix_refl _
  · rw [List.take_of_length_le hle, List.take_append,
      List.take_of_length_le hle]
    exact List.prefix_append _ _

/-- Full-cut availability is the completed pipeline value. -/
theorem availAt_full (env : List β →ₘ List α) (outs : List (List β)) :
    availAt env outs outs.length = env.f outs.flatten := by
  unfold availAt
  rw [List.take_length]

/-! ## Option A: the causal-cuts predicate (the knowledge face) -/

/-- **Causal cuts** (Option A): every prefix of consumed batches through
tick `t` stays within the availability generated by the outputs of ticks
`< t` — strictly, by tick atomicity (a tick's inputs are read before its
outputs are emitted). Multiset domination, matching `BatchLegal`. -/
def CausalCuts [DecidableEq α] (env : List β →ₘ List α)
    (outs : List (List β)) (d : List (List α)) : Prop :=
  ∀ t, t < d.length →
    ∀ v, ((d.take (t + 1)).flatten).count v ≤ (availAt env outs t).count v

/-- Elimination: an element consumed at tick `t` was producible from my
first `t` output ticks alone. -/
theorem CausalCuts.mem_availAt [DecidableEq α] {env : List β →ₘ List α}
    {outs : List (List β)} {d : List (List α)}
    (hc : CausalCuts env outs d) {t : Nat} (ht : t < d.length) {v : α}
    (hv : v ∈ d[t]'ht) : v ∈ availAt env outs t := by
  have hmem : v ∈ (d.take (t + 1)).flatten := by
    refine List.mem_flatten.mpr ⟨d[t]'ht, ?_, hv⟩
    rw [take_succ_eq d t ht]
    exact List.mem_append.mpr (Or.inr (List.mem_singleton.mpr rfl))
  exact List.count_pos_iff.mp
    (Nat.lt_of_lt_of_le (List.count_pos_iff.mpr hmem) (hc t ht v))

/-! ## Option C: the atomic-tick-region combinator (definitional) -/

/-- One location's atomic tick region against its environment (Option C):
tick `t` consumes the decided batch if it is `BatchLegal` against
`availAt env (outputs so far) t` minus prior consumption, then computes
this tick's outputs via `step`; otherwise the run blocks (exactly
`batchC`'s discipline with the constant availability generalized to the
guarded family). The accumulators make the guarded tick-indexed fixpoint
structurally recursive: this tick's output is appended only AFTER its
batch is drawn — the strict guard. -/
def causalTickLoop [DecidableEq α] (env : List β →ₘ List α)
    (step : σ → List α → σ × List β) :
    (s : σ) → (outs : List (List β)) → (consumed : List α) →
    (d : List (List α)) → List (List α × List β)
  | _, _, _, [] => []
  | s, outs, consumed, b :: ds =>
    if BatchLegal (availAt env outs outs.length) consumed b then
      (b, (step s b).2)
        :: causalTickLoop env step (step s b).1 (outs ++ [(step s b).2])
            (consumed ++ b) ds
    else []

/-- `batchC` is the constant-environment special case of
`causalTickLoop`: when the availability does not depend on my outputs,
the guarded family is constant and consumption coincides. -/
theorem causalTickLoop_const [DecidableEq α] {env : List β →ₘ List α}
    {avail : List α} (henv : ∀ l, env.f l = avail)
    (step : σ → List α → σ × List β) :
    ∀ (s : σ) (outs : List (List β)) (consumed : List α)
      (d : List (List α)),
      (causalTickLoop env step s outs consumed d).map Prod.fst
        = batchC avail consumed d
  | _, _, _, [] => rfl
  | s, outs, consumed, b :: ds => by
    unfold causalTickLoop batchC
    rw [show availAt env outs outs.length = avail from henv _]
    by_cases hb : BatchLegal avail consumed b
    · rw [if_pos hb, if_pos hb, List.map_cons]
      exact congrArg (b :: ·) (causalTickLoop_const henv step _ _ _ ds)
    · rw [if_neg hb, if_neg hb]
      rfl

/-- **Option A is Option C's elimination principle**: every realized
`causalTickLoop` run satisfies `CausalCuts` against its own realized
outputs — derived knowledge, never a hypothesis. -/
theorem causalTickLoop_causal [DecidableEq α] (env : List β →ₘ List α)
    (step : σ → List α → σ × List β) (s : σ) (d : List (List α)) :
    CausalCuts env
      ((causalTickLoop env step s [] [] d).map Prod.snd)
      ((causalTickLoop env step s [] [] d).map Prod.fst) := by
  suffices h : ∀ (s : σ) (outs : List (List β)) (consumed : List α)
      (d : List (List α)),
      (∀ v, consumed.count v ≤ (env.f outs.flatten).count v) →
      ∀ t, ∀ _ht : t < ((causalTickLoop env step s outs consumed d).map
          Prod.fst).length,
      ∀ v,
        (consumed
          ++ ((((causalTickLoop env step s outs consumed d).map
              Prod.fst).take (t + 1)).flatten)).count v
        ≤ (availAt env
            (outs ++ (causalTickLoop env step s outs consumed d).map
              Prod.snd)
            (outs.length + t)).count v by
    intro t ht v
    have := h s [] [] d
      (fun v => by rw [List.count_nil]; exact Nat.zero_le _) t ht v
    rwa [List.nil_append, List.nil_append, List.length_nil,
      Nat.zero_add] at this
  intro s outs consumed d
  induction d generalizing s outs consumed with
  | nil =>
    intro _ t ht
    exact absurd ht (by simp [causalTickLoop])
  | cons b ds ih =>
    intro hpre t ht v
    unfold causalTickLoop at ht ⊢
    by_cases hb : BatchLegal (availAt env outs outs.length) consumed b
    · rw [if_pos hb] at ht ⊢
      rw [availAt_full] at hb
      rw [List.map_cons, List.length_cons] at ht
      -- absorbing b stays within the completed-prefix availability
      have hstep : ∀ v, (consumed ++ b).count v
          ≤ (env.f outs.flatten).count v := by
        intro v
        by_cases hvb : v ∈ b
        · exact of_decide_eq_true (List.all_eq_true.mp hb v hvb)
        · rw [List.count_append,
            List.count_eq_zero_of_not_mem hvb, Nat.add_zero]
          exact hpre v
      cases t with
      | zero =>
        rw [List.map_cons, List.take_succ_cons, List.take_zero,
          List.flatten_cons, List.flatten_nil, List.append_nil,
          Nat.add_zero, List.map_cons]
        rw [show availAt env
            (outs ++ ((step s b).2
              :: (causalTickLoop env step (step s b).1
                  (outs ++ [(step s b).2]) (consumed ++ b) ds).map
                Prod.snd))
            outs.length
            = env.f outs.flatten from by
          unfold availAt
          rw [List.take_left]]
        exact hstep v
      | succ t' =>
        have hpre' : ∀ v, (consumed ++ b).count v
            ≤ (env.f (outs ++ [(step s b).2]).flatten).count v :=
          fun v => Nat.le_trans (hstep v)
            (count_le_of_prefix_d
              (env.mono (prefix_flatten ⟨[(step s b).2], rfl⟩)) v)
        have hrec := ih (step s b).1 (outs ++ [(step s b).2])
          (consumed ++ b) hpre' t' (by omega) v
        rw [List.map_cons, List.take_succ_cons, List.flatten_cons,
          List.map_cons]
        rw [show consumed ++ (b ++ (((causalTickLoop env step (step s b).1
              (outs ++ [(step s b).2]) (consumed ++ b) ds).map
              Prod.fst).take (t' + 1)).flatten)
            = (consumed ++ b) ++ (((causalTickLoop env step (step s b).1
              (outs ++ [(step s b).2]) (consumed ++ b) ds).map
              Prod.fst).take (t' + 1)).flatten from
          (List.append_assoc _ _ _).symm]
        have heq : availAt env ((outs ++ [(step s b).2])
            ++ (causalTickLoop env step (step s b).1
              (outs ++ [(step s b).2]) (consumed ++ b) ds).map Prod.snd)
            ((outs ++ [(step s b).2]).length + t')
          = availAt env (outs ++ ((step s b).2
              :: (causalTickLoop env step (step s b).1
                (outs ++ [(step s b).2]) (consumed ++ b) ds).map
                Prod.snd))
            (outs.length + (t' + 1)) := by
          rw [List.append_assoc, List.singleton_append,
            List.length_append, List.length_singleton,
            show outs.length + 1 + t' = outs.length + (t' + 1) from by
              omega]
        rw [heq] at hrec
        exact hrec
    · rw [if_neg hb] at ht
      exact absurd ht (by simp)

end HydroLean.Hydro
