#!/usr/bin/env node

import { App } from "aws-cdk-lib";
import { HydroEcsStack } from "./hydro-ecs-stack";
import * as path from "node:path";

const app = new App();

// The manifest is generated by: cargo run -p kvs --example kvs -- --mode export
// Default location is ./hydro-assets/hydro-manifest.json relative to the kvs crate root.
const manifestPath = app.node.tryGetContext("manifestPath")
    ?? path.resolve(__dirname, "../../hydro-assets/hydro-manifest.json");

// Docker build context is the workspace root (parent of kvs/)
const dockerContext = app.node.tryGetContext("dockerContext")
    ?? path.resolve(__dirname, "../docker");

new HydroEcsStack(app, "HydroKvsPublic", {
    manifestPath,
    dockerContext,
    env: {
        account: process.env.CDK_DEFAULT_ACCOUNT,
        region: process.env.CDK_DEFAULT_REGION ?? "us-east-1",
    },
});

app.synth();
