[package]
name = "hydroflow_core"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.0"
quote = "1.0.0"
slotmap = "1.0.6"
syn = { version = "1.0.0", features = [ "parsing", "extra-traits" ] }
