[package]
name = "analysis"
publish = false
version = "0.11.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/hydro-project/hydro"
description = "Dataflow analysis based on recorded performance."

[lints]
workspace = true

[dependencies]
regex = "1.11.1"